### ISSUE TITLE
Embedding model's accuracy doesn't consider the whole vocab in fasttext comparison tutorial

### ISSUE THREAD

**Issue by parulsethi** [RaRe-Technologies/gensim#1037]
In [Word2Vec_FastText_Comparison](https://github.com/RaRe-Technologies/gensim/blob/ba1ce894a5192fc493a865c535202695bb3c0424/docs/notebooks/Word2Vec_FastText_Comparison.ipynb), `acc = model.accuracy(questions_file)` doesn't consider whole vocab for models trained on large datasets (as default is upto 30000, ex. vocab size is approx. 71290 for text8), which considerably effects accuracy.
`acc = model.accuracy(questions_file, restrict_vocab=len(model.vocab))` solves it.

**Comment by tmylk** [comment]
cc @jayantj

**Comment by jayantj** [comment]
Thanks for pointing that out, good observation. Could you elaborate a little bit more on what you discovered about the effect of max vocab size on accuracy?

From what I have seen, choosing a larger value causes a significant drop in the accuracy, since the vectors for words beyond the first 30k are used too, which expands the set of "questions" answered, and they are mostly incorrectly answered, since the vectors learnt for the words tend to get less and less meaningful with decreasing frequency of the word.

An appropriate threshold would depend on the model vocab, the value of 30000 is suggested by the [original word2vec authors](https://github.com/tmikolov/word2vec/blob/master/compute-accuracy.c#L36) for fast approximate evaluation.

**Comment by parulsethi** [comment]
Oh yes. I missed the total testdata considered, and compared it to some other evaluation scheme(that doesn't skip OOV words).
Sorry!

**Comment by parulsethi** [comment]
It may be useful to make mention of `restrict_vocab` parameter in tutorial, but not changing it for the evaluation code.
Otherwise, we can close this issue I guess.
