### ISSUE TITLE
Multiple cores not being used in Word2Vec training

### ISSUE THREAD

**Issue by ELind77** [RaRe-Technologies/gensim#1112]
I've got a project with about 1000 novels (each ~150000 tokens) and I wanted to try out deepir.  I built the vocab and then trained and no matter how long I waited (1hr +) no more than one core was ever engaged.  I tried again with a test set (2 books, ~2e6 tokens) and got the same result.  

I looked through the code and found that `train` is using threading instead of multiprocessing, but since each thread is using a cython function that's supposed to unlock the GIL I'm not really sure how those two interact.  Is each thread supposed to unlock the GIL separately and get access to additional cores?

System:
Linux 14.04
`assert FAST_VERSION == 1` works fine
Tried with most recent release and 41ff1f431ec0c171e1433088c03a296aac6cf2d9

As an aside, I've found that for long-running jobs it's useful to kill and restart workers periodically to release memory, might not be a terrible idea here.

**Comment by gojomo** [comment]
The initial vocabulary-scan is single-threaded, but once training begins you should see multiple cores engaged, if you've used a `workers` parameter that starts multiple training threads. (You should see multiple cores engaged as soon as training begins.)

If you only ever see one core active, it's possible that your corpus iterator is the bottleneck. One thread iterates over your corpus – thus doing any IO or preprocessing/tokenization without parallelism – then passes chunks of work to the other worker threads. Only when those threads enter their cython-optimized sections, where they release the GIL, can other threads then also make progress, achieving parallelism. Since much of the data-handling is still in GIL-limited pure Python, the code still can't fully utilize large numbers of cores, but usually 4-8 can be seen at very high utilization. 

If you can move all laggy IO and complex processing out of your iterator – such as by working from lists-of-tokens in memory, or streaming from a very simply-delimited on-disk format – you may see much more parallelism. 

If you don't, let us know more about how you're monitoring CPU utilization, how your data is being fed to Word2Vec, and what training parameters you're using.

**Comment by ELind77** [comment]
@gojomo You're right, it was my iterator.  I was using spacy to do some processing.  I serialized the docs/sentences to plaintext files and it's using all cores now.

Thanks!
