### ISSUE TITLE
Use CoherenceModel in top_topics in LDAModel to avoid code duplication

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1128]
'u_mass' coherence is currently implemented in two places in gensim: CoherenceModel and LDAModel.

Use `CoherenceModel(coherence='u_mass', topn=num_words)` in LDAModel [`top_topics`](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/ldamodel.py#L824)

Will require changes to CoherenceModel to return non-aggregated coherence scores, topic words and avoid importing LDAModel.

**Comment by greninja** [comment]
I have a doubt regarding calculating the coherence of each individual topic.

Is it like:
We make a seperate 2D list of confirmation measures for each individual topic, in `direct_confirmation_measure.py`'s `log_conditional_probability` function, instead of creating one whole big list for all the topics combined, and then calculate the arithmetic mean of each topic to give its coherence?

This will I believe  generate non-aggregated coherence scores. I will make a PR accordingly.

**Comment by ismskd** [comment]
@tmylk dear
my spyder hangs whenever i use coherence='c_v' in CoherenceModel

`
Lda_Model = LdaModel(corpus=corpus, id2word=dictionary, iterations=50, num_topics=2)

cm = CoherenceModel(model=Lda_Model, texts=texts, dictionary=dictionary, coherence='c_v')
print( cm.get_coherence())`

plz guide me if u have any idea about this issue

**Comment by menshikh-iv** [comment]
@ismskd this related to Windows + Multiprocessing issue, see #2291
