### ISSUE TITLE
GenSim Install error

### ISSUE THREAD

**Issue by john-jh-lee** [RaRe-Technologies/gensim#1140]
Can anyone please help me install GenSim? 

I've installed Python 3.6 (32bit) and tried pip -U GenSim in the Command Prompt.
But as you can see in the last snapshot, there is install error. 

Any help would welcome! Thank you so much.

<img width="432" alt="image1" src="https://cloud.githubusercontent.com/assets/19709955/22825720/dce28392-ef5c-11e6-809b-b25e6c305e99.png">
<img width="710" alt="image2" src="https://cloud.githubusercontent.com/assets/19709955/22825728/e24a20c4-ef5c-11e6-8709-d77caf8ea47d.png">
<img width="837" alt="image3" src="https://cloud.githubusercontent.com/assets/19709955/22825732/e4b21ce0-ef5c-11e6-9846-ddaf7b9cf8de.png">

**Comment by gojomo** [comment]
From the last line of your output...

~~~
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\python36-32\\Lib\\site-packages\\numpy'
~~~

...this appears to be triggering on `numpy` installation – one of the gensim prerequisites – so is not likely specifically a gensim installation problem. It'd be worth trying just `pip install numpy` to see if that alone is enough to trigger the error – in which case you have a generic `pip` problem, or perhaps a `numpy`-specific problem, rather than a `gensim`-specific problem. 

Searching the web for your full final error message line – `PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\python36-32\\Lib\\site-packages\\numpy'` – gave a number of discussions of people having similar problems. 

[Here](http://stackoverflow.com/questions/32167418/python-pip-install-trouble-shooting-permissionerror-winerror-5-access-is) suggests you may need to do installs as the administrator account to resolve the error. (That is typically required if installing packages *globally*, but it's much better to use a "virtual environment" specific to your user/project – and might avoid any need for adiministrator-install permissions. Virtual environment support is [built-into Python 3.6](https://docs.python.org/3/tutorial/venv.html).)

[Here](https://github.com/conda/conda/issues/2893) suggests the error can also be triggered by antivirus software. If nothing else works, you could try disabling any such software and re-trying.

Looking closely at your error, it's odd that most of the filename paths in the stack frames have `\lib\` in all-lowercase, while the terminal error line involves an attempted directory-creation at a file-path that includes `Lib` with an uppercase-`L`. Not sure this is a key part of the error, but it's odd. 

Separately, the use of a 32-bit Python probably doesn't create any problems now, but you could have problems down the line. Lots of text-modelling tasks on large corpuses outgrow the memory-addressing limits of 32-bit software. Prefer a 64-bit Python build when possible, and especially if your machine has 4GB or more of RAM you'd like to use in Python tasks. 

(Personally, I also recommend using Linux, rather than Windows, for this sort of work, as most of the software involved is primarily developed on, and most-often used on, Linux/UNIX machines. So while the software generally is multi-platform and should work on Windows, the most testing has happened elsewhere, and somewhat more of the prior-discussions, or online people, available to help with troubleshooting have expertise specific to Linux/UNIX.)

**Comment by john-jh-lee** [comment]
Thank you so much, gojomo, for your helpful comments. I think I am getting close to solving this issue. Thank you for your great help!

**Comment by tmylk** [comment]
@john-jh-lee Have you been able to resolve this issue?

**Comment by john-jh-lee** [comment]
@tmylk Unfortunately, no. I think the reason (which I do not know at the moment) should be something very simple. It's very frustrating that I cannot even install GenSim.

**Comment by gojomo** [comment]
What error do you get if you try:
* use a 64-bit Python 3.6, and...
* create virtual-environment first, and pip-install gensim into it?

**Comment by tmylk** [comment]
Have you tried Anaconda? It is the best package and package-manager for windows

**Comment by aditya-iitd** [comment]
Just type -:" sudo chown -R $USER c:\\program files (x86)\\python36-32\\Lib\\site-packages\\numpy"
in the command prompt. It happens because you are not checking if you have permissions to open that path. This command will change the permissions on those folders.

**Comment by aditya-iitd** [comment]
If this does not work tell me I have another way that might work!

**Comment by john-jh-lee** [comment]
Many thanks to those who have commented. I was finally successful to get GenSim using Anaconda. I think my major problem was that I didn't have Administrator's write permission on some of the folders on my machine. Anyways, thank you all very much!

**Comment by gojomo** [comment]
Glad to hear that! Good luck!
