### ISSUE TITLE
Word2Vec.build_vocab(…, update=True) gives "ValueError: all the input array dimensions except for the concatenation axis must match exactly"

### ISSUE THREAD

**Issue by chaxor** [RaRe-Technologies/gensim#1162]
The`build_vocab` function does not work with the ability to update online.  

i.e.:

    model.build_vocab(sentences, update=False)

works fine, but

    model.build_vocab(sentences, update=True)

does not.

It provides the following error:

    ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by gojomo** [comment]
Is it possible that you're doing those two things in succession with the exact same corpus – and thus there are no new words in the second call, meaning a degenerate/corner-case update?

If so, it should probably be a no-op rather than an error. But also perhaps the return-value of `build_vocab()` should give some hint that no expansion occurred (and thus was an unnecessary call). 

Separately: I would be wary of trying to use this incremental-vocabulary-update feature with incremental new corpuses that might be small or even devoid of any new words – those are cases where any followup training with the new examples might be similarly unneeded or even destructive to the model's quality. (The incremental-vocabulary-expansion feature, and re-training, is best considered an experimental feature to be evaluated carefully – you can't count on the idea that a few more examples will always or even usually lead to overall model improvement, and thus 'online' is a bit of a misnomer.)

**Comment by gojomo** [comment]
Are you by chance passing the same `sentences` in consecutively, and thus on the 'update', there are no new words? 

There is somewhat of an expectation that the corpus for an update would contain new words, or else you wouldn't need to be calling `build_vocab(…, update=True)` at all. But it would probably be better for this to be a no-op, ideally with some return value hinting that no update occurred, than give an error. 

Separately, those cases where there are no words – perhaps because the new material is very small or very redundant with previous training – are also cases where subsequent training may not be a net benefit to the model. (This incremental-vocabulary-expansion option is best considered an experimental feature to should be evaluated carefully after each use – not a true 'online' training option where incremental new examples always or even usually lead to net improvements.) So I'd be wary of any process where an update-vocab is being casually called with small/redundant new batches.

**Comment by chaxor** [comment]
Thank you for your response, I did not realize I was using this improperly.  
My thought was this was a feature that allowed you to train the model such that when it encountered new data when being used, it would have the ability to incorporate that new data into it.  
I am hoping to use word embeddings in a domain for which new words are created within the text fairly often, so I was hoping to find a manner to do this without it throwing an error and halting the program at every new word that it finds after the model has been trained.
I apologize if i misunderstood the use for this feature.
Thank you for your help,  I will continue searching.

**Comment by tmylk** [comment]
It is not an issue but a better error message is needed.
