### ISSUE TITLE
Unexpected behavior of intersect_word2vec_format()

### ISSUE THREAD

**Issue by Tixierae** [RaRe-Technologies/gensim#1245]
#### Description
According to the [doc](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.intersect_word2vec_format), I was expecting in-vocabulary words without an entry in the binary file to be removed from the vocabulary:

> No words are added to the existing vocabulary, but intersecting words adopt the file’s weights, and non-intersecting words are left alone.

However, it seems that those words are kept, and their vectors are initialized in some way...

#### Reproducible example
```
import numpy as np
from gensim import utils
from gensim.models.word2vec import Word2Vec

my_sentences = [['John','is','quicker','than','Mary'],['the','quick','brown','fox','jumped','over','the','lazy','dog'],['I_am_an_unknown_word','I_am_another_unknown_word']]

# initialize word vectors
word_vectors = Word2Vec(size=300, min_count=1)

# create entries for the words in our vocabulary
word_vectors.build_vocab(my_sentences)

# fill entries with pre-trained word vectors
word_vectors.intersect_word2vec_format(path_to_pretrained_wv + 'GoogleNews-vectors-negative300.bin.gz', binary=True)
```
#### Expected Results
```
# I would expect True, i.e., vocab size to be equal to the number of unique words in our corpus - 2 (the two unknown words)
len(word_vectors.wv.vocab) == len(list(set([word for sent in my_sentences for word in sent]))) - 2 
```
#### Actual Results
```
# instead, the following returns True
len(word_vectors.wv.vocab) == len(list(set([word for sent in my_sentences for word in sent])))

# the 2 words without an entry in the binary file have been initialized. But how exactly? Randomly? With which formula? Why not to all zeroes?
# their norms are close to zero
norms = [np.linalg.norm(word_vectors[word]) for word in word_vectors.wv.vocab.keys()]
idxs_zero_norms = [idx for idx, norm in enumerate(norms) if norm<0.1]
[word_vectors.wv.vocab.keys()[idx] for idx in idxs_zero_norms]
```
I think the documentation should be made clearer, and the exact formula used to initialize the vectors for the unknown words should be given. Actually, maybe the user could select how to deal with those unknown words (removing them from vocab, initializing them to all zeroes, or random initialization)...

**Comment by gojomo** [comment]
The fact that the documentation says "non-intersecting words are left alone" was intended to communicate that the words remain exactly as they would normally be, at the end of `build_vocab()`. What about that made you think they'd be deleted? 

They are randomly-initialized exactly as all vectors have already been, in the usual case of simply preparing them for fresh training, by `build_vocab()` (specifically `reset_weights()`). The code follows the formula of the original Google word2vec.c code.

(The choice to bring in some extra words, via `intersect_word2vec_format()`, is an experimental feature and simply modifies existing words in-place to keep the code and possible model-states simple, compared to allowing arbitrary vocabulary changes after a model has already been initialized or trained.)

If you don't want certain words in your model before training, I'd recommend you leave those words out of the example texts used to construct the vocabulary. 

If you need the vocabulary to exactly match an external vector source, like the GoogleNews vectors, your example texts should be built from that file's word list. Though note, the resulting vocabulary wouldn't have the true word-frequency information needed for later training using negative-sampling of frequent-word downsampling. Also, calls to `train()` expect exactly as much training-text as was supplied to `build_vocab()` – if you're supplying different texts you'll need to add one of the explicit optional parameters to `train()` for specifying the total amount of text. 

If you need to do something highly custom, like zero out some vectors instead of using the customary pre-training initialzation, that'd best be done as your own code, mutating the model at the appropriate time. 

If you just need read-access to exactly the vectors in the GoogleNews set, for lookup or most-similar list results, there's no need to use `intersect_word2vec_format()` at all – `KeyedVectors.load_word2vec_format()` is a better choice.

**Comment by Tixierae** [comment]
Thanks much for the very quick reply and the clear explanations and tips!
