### ISSUE TITLE
Adapt the online w2v approach to doc2vec

### ISSUE THREAD

**Issue by medamm1993** [RaRe-Technologies/gensim#1277]
Is it possible to adapt the online w2v approach to support the doc2vec algorithm ?

**Comment by tmylk** [comment]
Vocabulary expansion for doc2vec is not a supported feature. The reason is that the value of this feature is not clear. There hasn't been a study on how useful are the results of this vocab-expansion technique.

Some people got it to work with hs=0 while other modes gave errors. See discussion in #1019
