### ISSUE TITLE
Phrase Detection

### ISSUE THREAD

**Issue by AaronWang30** [RaRe-Technologies/gensim#1280]
Suppose we have a sentence with 3 words ABC and both (A_B) and (B_C) could be a phrase based on their frequency. It looks like the algorithm now will not output a sentence (A_B) (B_C) but (A_B) C. Why did we design like this or is that a bug?

**Comment by gojomo** [comment]
I believe the code is based on the phrases feature that was released with Google's word2vec.c - and so operates in the same way, and in a greedy left-to-right fashion. (That is, phrase-promoting `A_B` precludes `B` from being available for consideration as part of `B_C`, even if the frequency-based analysis suggests `B_C` is a stronger phrase than `A_B`.) 

Also, many downstream uses wouldn't expect a unigram to be *repeated* upon phrase-promotion – so would expect to see `A B C` become *either* `A_B C` or `A B_C`, but not `A_B B_C`, since `B` only appeared once in the original content. 

I could envision some projects wanting such overlapping possibilities, with a downstream step helping to choose/filter legitimate phrases. (There might even be a role for a more-sophisticated data-structure than just a list-of-tokens, where multiple alternate tokenizations are represented in parallel, as a sort of directed-graph.)

**Comment by tmylk** [comment]
Closing as resolved if @AaronWang30 allows.
