### ISSUE TITLE
Strange vector Doc2vec

### ISSUE THREAD

**Issue by nazandr** [RaRe-Technologies/gensim#1283]
some vectors looks like
```
array([-0.00733526,  0.00999952, -0.01261605,  0.01011786,  0.07900785,
        0.04137786, -0.03732466,  0.05575992, -0.05047178,  0.02926481,
        0.07824577, -0.02072133,  0.04255045,  0.11130052,  0.01084163,
        0.10062899,  0.05395846, -0.06410903, -0.01366755, -0.11083295,
        0.12899043, -0.03809672, -0.09893423, -0.00773246,  0.05325002,
        0.07909556, -0.00914345,  0.02059805,  0.06765973,  0.065979  ,
       -0.11023469,  0.05267623, -0.0522052 , -0.02762912, -0.08300045,
        0.02127337, -0.02897984, -0.06673234,  0.12698697, -0.00603647,
```
but for some sentence return 
```
array([  4.09992076e-02,  -4.20646556e-02,  -3.93421054e-02,
         2.81166416e-02,   5.20429388e-03,  -6.09559268e-02,
        -7.50171319e-02,   2.51412187e-02,  -8.69358405e-02,
         2.34159864e-02,   4.12164405e-02,  -3.65364738e-02,
        -3.05360481e-02,   1.29881486e-01,   3.17426845e-02,
         7.04457983e-02,  -1.22882025e-02,  -7.52012432e-02,
        -4.12519686e-02,   9.38941818e-03,   1.74535215e-01,
        -9.55936536e-02,  -3.20684612e-02,  -4.96949479e-02,
         7.15341941e-02,   7.31820008e-03,   1.80403423e-02,
        -3.90936248e-02,  -6.45003747e-03,   1.33064881e-01,
```

**Comment by gojomo** [comment]
That's just a different form (scientific notation) of displaying floating-point numbers. For example, the 1st number in your top vector could have been displayed as `-7.33526e-03` – same number, different print-format. 

I'm not sure what rule numpy's ndarray class uses to choose one form or the other; it might be a matter of a single (or few, or early) values in a vector being larger than some threshold. Still, it's a superficial difference, and it appears possible to suppress scientific notation per the `suppress` option shown at: https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html

Note that the preferred forum for such general questions is the project discussion forum, https://groups.google.com/forum/#!forum/gensim – so that this github issue-tracker can remain focused on bugs & feature-requests.
