### ISSUE TITLE
Gensim error while loading Hebrew

### ISSUE THREAD

**Issue by guybartal** [RaRe-Technologies/gensim#1301]
#### Description
Gensim error while loading Hebrew

#### Steps/Code/Corpus to Reproduce
```
from gensim.models.wrappers import FastText
model = FastText.load_fasttext_format('wiki.he')
```
#### Actual Results
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-11-edebc82131f5> in <module>()
      2 
      3 #num_dims = 300
----> 4 model = FastText.load_fasttext_format('wiki.he')

/home/vmadmin/anaconda3/lib/python3.5/site-packages/gensim/models/wrappers/fasttext.py in load_fasttext_format(cls, model_file)
    236         model = cls()
    237         model.wv = cls.load_word2vec_format('%s.vec' % model_file)
--> 238         model.load_binary_data('%s.bin' % model_file)
    239         return model
    240 

/home/vmadmin/anaconda3/lib/python3.5/site-packages/gensim/models/wrappers/fasttext.py in load_binary_data(self, model_binary_file)
    253         with utils.smart_open(model_binary_file, 'rb') as f:
    254             self.load_model_params(f)
--> 255             self.load_dict(f)
    256             self.load_vectors(f)
    257 

/home/vmadmin/anaconda3/lib/python3.5/site-packages/gensim/models/wrappers/fasttext.py in load_dict(self, file_handle)
    274         (vocab_size, nwords, _) = self.struct_unpack(file_handle, '@3i')
    275         # Vocab stored by [Dictionary::save](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc)
--> 276         assert len(self.wv.vocab) == nwords, 'mismatch between vocab sizes'
    277         assert len(self.wv.vocab) == vocab_size, 'mismatch between vocab sizes'
    278         ntokens, = self.struct_unpack(file_handle, '@q')

AssertionError: mismatch between vocab sizes

#### Versions
Linux-4.4.0-75-generic-x86_64-with-debian-stretch-sid
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
NumPy 1.11.1
SciPy 0.18.1
gensim 1.0.1
FAST_VERSION 2

**Comment by matanster** [comment]
Looks a bity like https://github.com/RaRe-Technologies/gensim/issues/1236.
The error message might seem to imply a problem with fasttext. I am not sure whether fasttext is embedded/bundled with gensym or whether a newer version of fasttext might be tried as a workaround.

**Comment by kewlcoder** [comment]
Has this issue been resolved?
If yes, can you please share the reference?

**Comment by tmylk** [comment]
Hi @kewlcoder This is not an issue with gensim wrapper but an issue with the trained FastText model as there is a mismatch in vocab between .bin and .vec files. @prakhar2b , could you please investigate and raise an issue in FastText repo?

Please use `FastText.load_word2vec_format('FILENAME.vec')` as a workaround for now.

**Comment by prakhar2b** [comment]
@tmylk The mismatch is not only for the pretrained models released by facebook, we are getting this error for all the models trained by fasttext, which was not the case earlier. Something might have changed in the fastText, looking into the code to see if it's intentional, then I'll raise an issue in the fastText repo.

**Comment by jayantj** [comment]
The assertion to check for mismatch between vocab sizes between the `.vec` and `.bin` file was written as part of a defensive approach to make sure there weren't any "silent" bugs.
In case the mismatch doesn't make an actual difference, and it is possible to proceed with loading the model, changing the assert to a warning log would be a decent solution.

**Comment by dgg5503** [comment]
About 8 days ago, fastText added two additional int32_t's to the .bin model header. These are "magic" and "version." As of right now, fasttext.py does not account for these integers when reading in model parameters causing it to be off by 2 integers for the rest of the reads. Take a look at the "checkModel" function in https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc to see what I'm talking about.

**Comment by prakhar2b** [comment]
@dgg5503 @tmylk @jayantj  struct_unpack for models trained by fastText -
```(self.wv.vocab from .vec file, nwords & vocab_size from .bin using struct.unpack)```

parameter  | fastText (old) | fastText(new)
-------------  | ----------------  | ----------------
len(self.wv.vocab) | 71290 | 71290
nwords | 71290 | 1058682594
vocab_size | 71290 | -350469331

It's not because of addition of `magic` and `version` variable or because of dictionary pruning. FastText has recently added a few functions in `fasttext.cc` like `selectEmbeddings` , `sentenceVectors` etc.   `vec` file is simply a text file for word vectors, therefore these additional parameters have caused a mismatch from `bin` file.

I'm not sure why we have negative value for vocab_size. @jayantj (please comment on this). If this is undesirable, we should report it to fastText repo.

Also, if this is an intentional mismatch (which seems to be), then there is no point in making any assert or warning statement. I think we should use vec and bin file separately for different purposes assuming that facebook's fastText code is working fine. This was also discussed for [issue #1261](https://github.com/RaRe-Technologies/gensim/issues/1261) (improving fasttext loading time) while making comparision with salestock's fasttext loading mechanism which only used bin file for loading.

**Comment by jayantj** [comment]
@prakhar2b Are you sure about this? Looking at those values, it seems very likely to me that we are reading the wrong bytes for the values of `nwords` and `vocab_size`.

Also, on a different note: the issue raised about the model trained on French wiki is quite old, before the FastText `magic` or `version` variables were added. I believe they are probably two different issues.

**Comment by prakhar2b** [comment]
UPDATE : I've solved this. I'll submit a final PR asap. @dgg5503  Indeed magic and version variable caused this error. Thanks for pointing this out.

**Comment by olivierhub** [comment]
The problem looks deeper than an offset problem. 
French embeddings ( and probably hebrew ones also ) work with utf-8, and the dictionary code:
https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc
does not seem to be utf-8 aware:
in the ::save and ::load methods,
End of word is marked / detected with a (char) 0
save:
out.write(e.word.data(), e.word.size() * sizeof(char));
    out.put(0);
load:
 char c;
    entry e;
    while ((c = in.get()) != 0) {

this probably does not work fine with utf-8 words. 
In the fasttext python wrapper there is a sanity check once a "detected word" is read:
gensim/models/wrappers/fasttext.py
def load_dict(..)
  ...
  assert self.wv.vocab[word].index == i,

this line fails  with the parsing of the first word of the wiki.fr.bin file because word is empty and so is not in the vocab dictionary (Key Error ).

Did someone already had some success using the non-english binary files?
