### ISSUE TITLE
dependency on bz2

### ISSUE THREAD

**Issue by dcsan** [RaRe-Technologies/gensim#1488]
#### Description
Python on ubuntu seems to not ship with bz2 library working. It requires recompiling python from source. 
Simply `import gensim` will throw the error below, resulting in hours trying to recompile python, and other difficulties with virtual environments that don't find the system library.

Can this dependency be removed? if it is only required for downloading/uncompressing  corpora, this can be done offline in a development environment. Currently gensim is hard to use in a production environment because of the setup nightmare below.

```python
Traceback (most recent call last):
  File "webrun.py", line 5, in <module>
    from webapp import routes
  File "/opt/rikai/webnlp/app/webapp/routes.py", line 13, in <module>
    import webnlp.wrapper
  File "/opt/rikai/webnlp/app/webnlp/wrapper.py", line 12, in <module>
    import classifier.classifier
  File "/opt/rikai/webnlp/app/classifier/classifier.py", line 9, in <module>
    import gensim
  File "/opt/rikai/webnlp/venv/lib/python3.6/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/opt/rikai/webnlp/venv/lib/python3.6/site-packages/gensim/corpora/__init__.py", line 14, in <module>
    from .wikicorpus import WikiCorpus
  File "/opt/rikai/webnlp/venv/lib/python3.6/site-packages/gensim/corpora/wikicorpus.py", line 21, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 23, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
```

#### Steps/Code/Corpus to Reproduce
Launching any app that will `import gensim` causes an immediate halt

https://stackoverflow.com/questions/12806122/missing-python-bz2-module/45149817#45149817

**Comment by gojomo** [comment]
Are you using the Ubuntu-bundled version of Python, or something installed from official repositories? Because I would think any proper Python install would include the core BZ2 support – and the SO answer you link suggests this problem would only occur if compiling one's own Python, and not having bzip2-headers available when that happens.

**Comment by dcsan** [comment]
tx for the reply. yes I am using python 3.6 and ended up having to compile it from source. I eventually did add the lib-devel files in.
If i just want to use the classifier parts of gensim without importing the corpora and it's deps, then if I am more specific about the imports this maybe avoidable in future?

**Comment by gojomo** [comment]
I suspect compiling-from-source was the start of your problem. I doubt there would be any problems with `import bz2` in a Python that was installed via the usual Ubuntu packaging sources  – or using whatever Python was installed as part of the base system.

 So I believe the proper (and only) recommendation appropriate here is: have a full/working Python before attempting to use gensim.

**Comment by piskvorky** [comment]
Agreed. The `bz2` module is a part of Python's standard (built-in) library.

If we started checking and making exception for missing standard libraries, we'd never stop.

Closing here -- I'd suggest you open an issue with the distribution that ships an incomplete Python (`Python on ubuntu seems to not ship with bz2 library working.`), because that's the real problem. I except you'll have issues in many other places like this, not only gensim.
