### ISSUE TITLE
Class Similarity don't work with million document?

### ISSUE THREAD

**Issue by bobbylz** [RaRe-Technologies/gensim#1526]
#### Description
I have 1.7 million document, and I want to get the similarity of documents. code:
...
index = similarities.Similarity(corpus, num_features=200000) 

x = index.similarity_by_id(0) #The process is still alive, but stay here over 30 hours,bug???

and I found the point, it stay here and do not leave out:
result = self.index * query.tocsc()  # N x T * T x C = N x C

TODO: change commented example

**Comment by menshikh-iv** [comment]
For such a large number of documents, it is better to use some approximate "search engines" like [annoy](https://github.com/spotify/annoy), [faiss](https://github.com/facebookresearch/faiss), etc.

**Comment by piskvorky** [comment]
@bobbylz Your corpus is still tiny, 1.7 million documents is no issue. Other libraries like Annoy of FAISS will have the same problem -- in fact, even worse, because they do not support sparse vectors at all.

The problem is the dimensionality: 200,000. Can't you perform dimensionality reduction first (LSI etc)?

If not, and your 200,000 dimensions are sparse (bag-of-words), I'd suggest using some fulltext engine with inverted index.
