### ISSUE TITLE
LDAModel, HDPModel and LDAMultiCore using all the cores

### ISSUE THREAD

**Issue by Diego999** [RaRe-Technologies/gensim#1532]
Hi,

I was tweaking the parameters of different models to further run random search with multiple parallel instances. I set up number of processes to 3 when it was needed (CoherenceModel and LDAMultiCore) and I realized that even with the number of processes specified, all the cores were used. Same observation for sequential model such as LDAModel and HDPModel.

I found a workaround using:

`export OMP_NUM_THREADS=1 && python3 myfile.py` and set the number of cores according to the API for LDAMultiCore & CoherenceModel.

Are you aware of this behavior ?

I'm using python 3.5 and run on Linux environment. I didn't find this behavior on Mac OS

**Comment by piskvorky** [comment]
IIRC, these methods allow you to set the number of workers (not processes). So the number of processes will be ~`workers+1`, because there's the main process too (which prepares the data & aggregates the results from workers).

So if you have 4 cores, it is expected all of them will be busy if workers=3.

If you have more than 4, the likely reason is parallelization inside numpy. All these models use numpy heavily underneath, for matrix/vector multiplications. So if your numpy uses some parallelized BLAS underneath (OpenBlas, MKL etc), even a single Python thread/process can utilize all cores.

Can you confirm your numpy parallelization, with something like `x = np.random.rand(1000, 1000); np.dot(x, x)`?

**Comment by Diego999** [comment]
I did `x = np.random.rand(10000, 10000); np.dot(x, x)` and I can confirm that by default, it takes all the cores on my Linux system (~20).

**Comment by piskvorky** [comment]
So that's the answer there :) `OMP_NUM_THREADS=1` will stop numpy from using more than one core, so that then one worker process ~= one core, as you'd expect.

Can we close now?

**Comment by Diego999** [comment]
Yes :) thank you very much !
