### ISSUE TITLE
Building Vector for a sentence in doc2vec from an untrained data set

### ISSUE THREAD

**Issue by codehumanity** [RaRe-Technologies/gensim#1586]
I do have a dataset (corpus size = 6 million).

Environment And Package Version:
`Linux-3.10.0-327.18.2.el7.x86_64-x86_64-with-redhat-7.2-Maipo`
`Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) `
`[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]`
`NumPy 1.13.1`
`SciPy 0.19.1`
`gensim 2.3.0`
`FAST_VERSION 1`

I have trained the Doc2Vec model using below steps and parameters:
Step 1: Preprocessing:
Change to lower case

Step 2: Preparing the Tagged Document.

`docs = []`
`docs = [TaggedDocument(words = desc.split(),tags=[df['UNQ_ID'].ix[idx]]) for idx,desc in` `enumerate(df['DOCUMENT'].values)]`

Step 3: Model Training.

`iteration = 150`
`model = gensim.models.Doc2Vec(size=300, window=8, min_count=5, workers=8,   iter=iteration)`
`model.build_vocab(docs)`
`model.train(docs, total_examples=model.corpus_count, epochs=model.iter)`

Step 4: Save the Model.

`model.save(SAVE_NAME)`

Step 5: Find Similarity:

`UNIQUE_ID='XXX'`
`sims = mod.docvecs.most_similar(UNIQUE_ID, topn=5)`

For existing trained documents, the similarity score is above 0.8 on the average. This is good as per my use case.

There are cases. when new untrained documents are encountered.
Those scenarios, give below error:
TypeError: '<' not supported between instances of 'str' and 'int'

I tried using infec_vector() using below steps and parameters.

`UNIQUE_ID='XXX'`
`try:`
`            sims = mod.docvecs.most_similar(UNIQUE_ID, topn=5)`
`            print("EXECUTING REGULAR mod.docvecs.most_similar")`
`except:`
`            token = df.loc[df['UNQ_ID']==UNIQUE_ID].DOCUMENT`
`            token = token.str.split()`
`            mod.random.seed(0)`
`            new_vector = mod.infer_vector(token, steps=150)`
`            sims = mod.docvecs.most_similar([new_vector], topn=5) `
`            print("EXECUTING infer_vector mod.docvecs.most_similar")`
`sims`

But the similarity score is very less; for the inferred vectors.

Please let know, is there any way through which we can better logical similarity score for untrained documents.

Or other way around, how can we do real time training for Untrained documents.

Googling Around: I got below link: 
[https://stackoverflow.com/questions/32796485/building-vector-for-a-sentence-in-doc2vec-from-an-untrained-data-set?rq=1]
But in latest Gensim version (Gensim 2.3.0), we need to build_vocab before train. In real time, build_vocab for entire data set, will take more time.

`Note:`
Fixed the non-deterministic behaviour of infer_vector() using this link:
https://github.com/RaRe-Technologies/gensim/issues/447

**Comment by gojomo** [comment]
For the reported `TypeError: '<' not supported between instances of 'str' and 'int'`, there's not enough info to determine what's triggering this. If this is a continuing concern, please include the exact code which triggers and full error-stack.

For the unexpectedly-low similarity scores with inferred-vectors, usually such issues are a matter of ensuring that both the initial training, and later inference, are done with sensible parameters/texts, checking interim results along the way.  Re-inferring one of the original training docs, as you've done, and comparing its inferred vector (and most-similars) against the same results from looking up the bulk-trained tag vector is a good sanity check – the top-N most-similars should be very similar (though not identical). If they're not, you'd ensure the tokenized texts were really identical in both tests, try other inference parameters, and double-check that real training with adequately balanced parameters/data was happening in the 1st place. 

Not sure what you mean by "real time training for Untrained documents". While you can continue to `train()` a `Doc2Vec` model with new documents, there's not yet any supported facility for expanding the vocabulary (so any new words are ignored), and there are difficult open questions of training-balance which must be considered in the choice of learning-rate, iterations, and influence of earlier training. So there's no straightforward technique, or recommendations for good results – just things an expert operator could experiment with. 

Open-ended questions are better handled in the project's discussion forum, <https://groups.google.com/forum/#!forum/gensim>, rather than this bug-tracker. So unless there's a clear bug here, I'll close this issue – and please ask future or followup questions on that forum.

**Comment by souveekbose** [comment]
I am facing the same issue. 
gensim: 2.3.0
Python 3.6.0

**My code follows:**

def vectorize_doc2vec():
    sentence1 = 'Dogo is a dog'
    sentence2 = 'dog is a pet'
    sentence3 = 'pets are cool'
    sentence={sentence1:'j1', sentence2:'j2', sentence3:'j3'}
    
    sentences = LabeledLineSentence(sentence)
    
    model = Doc2Vec(min_count=1, window=10, size=100, sample=1e-4, negative=5, workers=8)
    model.build_vocab(sentences.to_array())
    
    model.train(sentences.sentences_perm(), total_examples=model.corpus_count, epochs=10)
    
    print(model.docvecs.most_similar('dog', topn=1))

vectorize_doc2vec()

**The class LabeledLineSentence is as follows:**

class LabeledLineSentence(object):
    def __init__(self, sources):
        self.sources = sources
        
        flipped = {}
        
        # make sure that keys are unique
        for key, value in sources.items():
            if value not in flipped:
                flipped[value] = [key]
            else:
                raise Exception('Non-unique prefix encountered')
    
    def __iter__(self):
        for description, id in self.sources.items():
            yield LabeledSentence(description, id)

    def to_array(self):
        self.sentences = []
        for description, id in self.sources.items():
            self.sentences.append(LabeledSentence(description, id))
        return self.sentences
    
    def sentences_perm(self):
        shuffle(self.sentences)
        return self.sentences

**Error StackTrace:**

INFO:gensim.models.doc2vec:collecting all words and their counts
WARNING:gensim.models.doc2vec:Each 'words' should be a list of words (usually unicode strings).First 'words' here is instead plain <class 'str'>.
INFO:gensim.models.doc2vec:PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
INFO:gensim.models.doc2vec:collected 14 word types and 4 unique tags from a corpus of 3 examples and 38 words
INFO:gensim.models.word2vec:Loading a fresh vocabulary
INFO:gensim.models.word2vec:min_count=1 retains 14 unique words (100% of original 14, drops 0)
INFO:gensim.models.word2vec:min_count=1 leaves 38 word corpus (100% of original 38, drops 0)
INFO:gensim.models.word2vec:deleting the raw counts dictionary of 14 items
INFO:gensim.models.word2vec:sample=0.0001 downsamples 14 most-common words
INFO:gensim.models.word2vec:downsampling leaves estimated 1 word corpus (3.7% of prior 38)
INFO:gensim.models.word2vec:estimated required memory for 14 words and 100 dimensions: 20600 bytes
INFO:gensim.models.word2vec:resetting layer weights
INFO:gensim.models.word2vec:training model with 8 workers on 14 vocabulary and 100 features, using sg=0 hs=0 sample=0.0001 negative=5 window=10
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 7 more threads
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 6 more threads
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 5 more threads
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 4 more threads
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 3 more threads
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 2 more threads
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 1 more threads
INFO:gensim.models.word2vec:worker thread finished; awaiting finish of 0 more threads
INFO:gensim.models.word2vec:training on 380 raw words (77 effective words) took 0.0s, 3374 effective words/s
WARNING:gensim.models.word2vec:under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha decay
INFO:gensim.models.doc2vec:precomputing L2-norms of doc weight vectors
Traceback (most recent call last):

  File "<ipython-input-54-d31b6431be4d>", line 17, in <module>
    vectorize_doc2vec()

  File "<ipython-input-54-d31b6431be4d>", line 14, in vectorize_doc2vec
    print(model.docvecs.most_similar('dog', topn=1))

  File "C:\Users\humblebee\AppData\Local\Continuum\Anaconda3\lib\site-packages\gensim\models\doc2vec.py", line 461, in most_similar
    elif doc in self.doctags or doc < self.count:

TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by baruaranojoy** [comment]
What is the standard dataset for generating an doc2vec model ?

**Comment by baruaranojoy** [comment]
Thank you for the help
