### ISSUE TITLE
Word2Vec RAM error when vector size is large

### ISSUE THREAD

**Issue by Aureth** [RaRe-Technologies/gensim#1601]
I'm using word2vec model on MacBook with 16GB of RAM. The input text is 45GB in h5df. 

When the vector size is 50. It runs successfully. When the vector size is 100, it prints

>2017-09-28 14:52:30,736 : INFO : PROGRESS: at 0.29% examples, 42940 words/s, in_qsize 0, out_qsize 0
>Killed: 9 

How can I solve this error?

**Comment by gojomo** [comment]
The Word2Vec implementation requires two giant arrays representing the word vectors, and the internal neural-network weights, to be in addressable memory. Both of these become larger as a function of retained-vocabulary-count, and vector-size. (The size of the training corpus, if streamed from IO sources properly, doesn't matter, except via the number of unique words it contains.) 

There should be some log lines before the one you've shared which report the retained vocabulary size, and even some rough estimates of the required memory for the model. If those numbers are larger than the system's addressable-memory, the model won't fit. 

If your system doesn't have enough memory, the options are (1) use a smaller vector `size`; (2) use a larger threshold `min_count` to discard more low-frequency words; (3) move to a system with more RAM. 

Usually, though, you'd get this error *before* any training-`PROGRESS` log lines – because the model essentially does its full preallocation of needed memory *before* any training starts. So it is likely some other process or library in play is surging its own memory-use after training starts. (It might be whatever's being used to read the HDF5 data.) Still, if that other process/code stays within a manageable constant amount of memory in the 50-dimension case, the key issue remains not having enough memory for the chosen model parameters.

**Comment by Aureth** [comment]
Thank you. Right now I am splitting the input data into chunks to fit the model and It seems that I can successfully train it.
