### ISSUE TITLE
Add "DOI badge" to gensim

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#1610]
Gensim's DOI is `10.13140/2.1.2393.1847`; the badge link should lead to https://www.researchgate.net/publication/255820377_Software_Framework_for_Topic_Modelling_with_Large_Corpora?channel=doi&linkId=0c960528f6404db272000000&showFulltext=true

(I saw this badge in https://github.com/tqdm/tqdm via #451 ; the goal is to promote more citations)

**Comment by souravsingh** [comment]
Sorry to chime in this issue. I believe the DOI which was added to the ``tqdm`` is a Zenodo generated DOI, which changes with versions.

**Comment by piskvorky** [comment]
Ah, thanks!

Is there a badge-generating service where we can select the text (and link) ourselves? Or we could just use our own image (static), I guess. Looks simple enough.

**Comment by souravsingh** [comment]
I haven't seen a badge which links to the paper, but it should be possible to create a badge which links to the paper on Gensim, since the badges are SVG icons.

On second thought, Having a Zenodo-generated DOI is not a bad idea. It is somewhat of a norm for scientific Python libraries to have a DOI so users can cite the DOI of the exact version for reproducibility.

**Comment by souravsingh** [comment]
Hello, Here is a basic badge which we can use- https://img.shields.io/badge/cite-paper-brightgreen.svg

**Comment by menshikh-iv** [comment]
Useful link: https://shields.io/
