### ISSUE TITLE
Under utilization of CPU cores when running Word2Vec

### ISSUE THREAD

**Issue by manneshiva** [RaRe-Technologies/gensim#1617]
#### Description
I am training a word2vec model with a preprocessed wiki corpus(~8GB) on a dedicated Softlayer cloud instance with the following system configuration:
`56 cores x 2.0GHz, 128GB RAM, 100GB(SAN), Ubuntu Linux 16.04 LST Minimal Install (64 bit).`
I run the code in a docker with **56 workers**. While I can see 56 processes(in training phase), the aggregated CPU utilization is around **1100%**. Screenshots of CPU utilization of each process can be seen below.
Why is total CPU utilization not around 5600%? Is this behavior expected? Am I missing something trivial?

#### Steps/Code/Corpus to Reproduce
Link to gensim [code](https://github.com/manneshiva/benchmark-word2vec-frameworks/blob/master/nn_frameworks/gensim/gensim_word2vec.py)
Link to [Dockerfile](https://github.com/manneshiva/benchmark-word2vec-frameworks/blob/master/Dockerfile-cpu-tfsource)

#### Expected Results
Total CPU utilization > 1100%. Should be around 5600%. 

#### Actual Results
Link to [INFO logs](https://gist.github.com/manneshiva/c4b7fd200507664fa3145b591be17be7).

`top -H -p <PID>`
![top](https://user-images.githubusercontent.com/26998249/31368736-300b7624-ad9d-11e7-9c38-4876e8d679af.png)

`htop`
![selection_006](https://user-images.githubusercontent.com/26998249/31368794-828f3714-ad9d-11e7-8a58-bafe552b3fae.jpg)

#### Versions
Linux-4.10.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
('Python', '2.7.12 (default, Nov 19 2016, 06:48:10) \n[GCC 5.4.0 20160609]')
('NumPy', '1.13.1')
('SciPy', '0.19.1')
('gensim', '2.1.0')
('FAST_VERSION', 1)

**Comment by gojomo** [comment]
Known limitation of current implementation. See related discussion in issues like #1486, #1291, #532, & #336. There are tips in those issues to improve parallelization, for example by optimizing the corpus iteration in the master thread or choosing different training parameters, but even after that the optimal throughput you'll find (via experimentation) will likely be with a `workers` count in the 3-16 range, rather than the full number of cores available.

**Comment by gojomo** [comment]
#336 will be the preferred issue for this limitation from here forward.
