### ISSUE TITLE
Remove init_sims from Word2Vec.load_word2vec_format

### ISSUE THREAD

**Issue by moustaki** [RaRe-Technologies/gensim#163]
Hello,

For large corpora, syn0norm can take a lot of memory and is only required when using most_similar. There is already a init_sims call in most_similar, so it is probably not needed in load_word2vec_format. Removing it would mean a smaller memory footprint when loading a new model, until most_similar is called.

https://github.com/piskvorky/gensim/blob/develop/gensim/models/word2vec.py#L377

Best,
y

**Comment by monajalal** [comment]
quick question, would the wdm distance change using gensim package if I use or not use `model.init_sims(replace=True)` ? I am trying to figure what's the effect of this piece of code? @piskvorky

**Comment by gojomo** [comment]
@monajalal – Looking at our implementation of `wmdistance()`, it appears the pairwise word distance calculation is using the 'raw' vectors (essentially, the contents of `syn0`). (See https://github.com/RaRe-Technologies/gensim/blob/68db4da59b63d12eab688a72bc008625387c77c0/gensim/models/word2vec.py#L1407 ) I'm not sure that this is correct – it might be more appropriate to use the same unit-normalized values that are used for cosine-similarity comparisons. But given the current calculation, since `init_sims(replace=True)` does in fact change `syn0`, any subsequent WMD calculations will also be changed by a `replace=True` operation.

**Comment by piskvorky** [comment]
@monajalal please use the mailing list for general questions, or open a new issue for reporting a bug (see [CONTRIBUTING.md](https://github.com/RaRe-Technologies/gensim/blob/develop/CONTRIBUTING.md)).

By hijacking an unrelated closed issue, fewer people can see it and respond, and any responses are wasted and hidden. Thanks.
