### ISSUE TITLE
Parameter `work` does not seem to end up being used in `train_document_dbow()`

### ISSUE THREAD

**Issue by rwberendsen** [RaRe-Technologies/gensim#1748]
https://github.com/RaRe-Technologies/gensim/blob/b6234e7d90ffe9aeda7fab4b39c484381d7c5930/gensim/models/doc2vec.py#L769

By just eyeballing the code, it seems that in this particular function call (and the similar function calls below it), the value passed in `work` is not used inside `train_document_dbow()`. I'm not saying I think it should be used, but if it is not used, perhaps it is cleaner not to pass it in the first place.

**Comment by gojomo** [comment]
Note that most users should be (and are) using the alternate `train_document_dbow()`  implementation in `doc2vec_inner.pyx`. That *does* use `work`, superficially, but really doesn't need to (as it'll allocate the scratch space it needs if not already provided, and there's no current need to share the object/memory back out to the caller at the end). 

I'm not sure why the original signatures for these methods used this pre-allocation-outside; it was probably an attempt at making the cythonized versions either more efficient or more transparent but isn't really serving any role now. Still, barring a larger refactoring for efficiency/clarity, cleaning up these little harmless inefficiencies, where everything is otherwise working. may not get much priority.

**Comment by piskvorky** [comment]
Like @gojomo says, `work` is a preallocated scratch space, used to speed up training (dynamically allocating arrays is very slow, plus ruins CPU caches, which are very important in tight loops).

Makes no different to the "pure Python" code path, which is slow anyway.
