### ISSUE TITLE
New Feature save_fasttext_format ? 

### ISSUE THREAD

**Issue by saroufimc1** [RaRe-Technologies/gensim#1782]
Hi, 
Are there plans to release the feature save_fasttext_format based on save_word2vec_format but for FastText? If so when are you planning to release it?
Currently, we have to use load and save, which saves the whole model. If we do not want to continue training it, we only need the .wv attribute, which is smaller in size than the whole model object... 

Thanks,
Carl

**Comment by menshikh-iv** [comment]
Hi @saroufimc1, thanks for the issue.

wdyt @manneshiva @jayantj?

**Comment by jayantj** [comment]
This is exactly the motivation behind having the `KeyedVectors` instance in the model - the `.wv` attribute that you mention.
You can do `model.wv.save('filename')` in order to save the `FastTextKeyedVectors` instance to a file.
Note that to load this saved file, you will need to use `FastTextKeyedVectors.load('filename')`.

Do let us know if this doesn't accomplish what you had in mind.

**Comment by saroufimc1** [comment]
Thanks @jayantj !

**Comment by menshikh-iv** [comment]
Thanks @jayant, 
@saroufimc1 I think that I should close current issue (problem resolved)

**Comment by saroufimc1** [comment]
Hello, I am opening this again after looking into the answer of @jayantj. 
Can't find  FastTextKeyedVectors.load('filename').
There is only load_word2vec_format in that class and it is not even working (it raises an error because it is not implemented yet.)

**Comment by menshikh-iv** [comment]
@saroufimc1 this works with latest gensim version `3.2.0`, update your gensim version.
