### ISSUE TITLE
Swapped edges in the Poincare embeddings code ?

### ISSUE THREAD

**Issue by octavian-ganea** [RaRe-Technologies/gensim#1855]
#### Description
Directed edges of the Wordnet transitive closure (directed acyclic graph) used in the Poincare embeddings code are swapped in the input file wordnet_noun_hypernyms.tsv and they are never swapped back in the actual code. Why ? 

#### Steps/Code/Corpus to Reproduce
Edges are not swapped back in all the places in the Gensim Poincare implementation, e.g. in the function get_root_and_leaf_nodes from docs/notebooks/Poincare%20Evaluation.ipynb . The original wordnet_file with swapped edges is here: https://github.com/jayantj/gensim/raw/wordnet_data/docs/notebooks/poincare/data/wordnet_noun_hypernyms.tsv

If not processed with the correct direction of the edges, this affects both training and evaluation. Is there any explanation for this ?

**Comment by menshikh-iv** [comment]
Thanks @octavian-ganea.
@jayantj can you elaborate?

**Comment by jayantj** [comment]
Hi @octavian-ganea , thanks for bringing this up.

I'm not entirely clear what you mean by "swapped". Swapped with respect to what?

The wordnet directed graph can be either one representing hypernymy relations, or one representing hyponymy relations. Poincare embeddings make use of hypernymy relations.

A hypernym relation (A, B) means that A is a type of B (otherwise known as an _is-a_ relation), and this is the order present in the expected input file, and also the file you've linked. Example: `cat.n.01	mammal.n.01` is a hypernymy relation, and `mammal` is a hypernym of `cat`.

**Comment by octavian-ganea** [comment]
Ok, thanks for explaining this. Now I see that in the NIPS paper they use (u,v) to refer to a hypernym relation, as opposed to the standard notation for edges in DAGs. However, I was confused by your function `get_root_and_leaf_nodes(data_file)` in which you process the edges as they were hyponym, not hypernym:
```    
    
root_candidates = set()
    leaf_candidates = set()
    with open(data_file, 'rb') as f:
        for line in f:
            nodes = line.split()
            root_candidates.update(nodes)
            leaf_candidates.update(nodes)
    
    with open(data_file, 'rb') as f:
        for line in f:
            node_1, node_2 = line.split()
            if node_1 == node_2:
                continue
            leaf_candidates.discard(node_1)
            root_candidates.discard(node_2)

```
However, the way this function is used is not affected by this.
