### ISSUE TITLE
Gensim's load fails to load a saved model 

### ISSUE THREAD

**Issue by dotslash** [RaRe-Technologies/gensim#1936]
#### Description
I was trying to load fasttext embedding into Word2Vec. The load time is very slow. (10 mins). So I was trying out if saving and loading the model will be faster. However the load step is failing.

#### Steps/Code/Corpus to Reproduce
model_file = '/path/to/original'
saved_model = '/path/to/save'
model = gensim.models.KeyedVectors.load_word2vec_format(model_file)
model.save(saved_model)
model = Word2Vec.load(saved_model)

#### Actual Results
The load step fails with the following error.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.envs/dspy3/lib/python3.5/site-packages/gensim/models/word2vec.py in load(cls, *args, **kwargs)
    974         try:
--> 975             return super(Word2Vec, cls).load(*args, **kwargs)
    976         except AttributeError:

~/.envs/dspy3/lib/python3.5/site-packages/gensim/models/base_any2vec.py in load(cls, *args, **kwargs)
    629         model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
--> 630         if model.negative and hasattr(model.wv, 'index2word'):
    631             model.vocabulary.make_cum_table(model.wv)  # rebuild cum_table from vocabulary

AttributeError: 'Word2VecKeyedVectors' object has no attribute 'negative'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-18-7af8ac3135e5> in <module>()
----> 1 model = LogExecTime("LoadSaved", LoadSaved)

<ipython-input-17-2402a78ca1d2> in LogExecTime(name, f, *args)
      7   start = time.time()
      8   print("Starting {}".format(name))
----> 9   ret = f(*args)
     10   print("{} took {} secs".format(name, time.time()-start))
     11   return ret

<ipython-input-17-2402a78ca1d2> in LoadSaved()
     23 def LoadSaved():
     24     saved_model = os.path.expanduser("~/code/fb.fasttext/crawl-300d-2M.vec.gensim")
---> 25     return Word2Vec.load(saved_model)
     26 
     27 

~/.envs/dspy3/lib/python3.5/site-packages/gensim/models/word2vec.py in load(cls, *args, **kwargs)
    977             logger.info('Model saved using code from earlier Gensim Version. Re-loading old model in a compatible way.')
    978             from gensim.models.deprecated.word2vec import load_old_word2vec
--> 979             return load_old_word2vec(*args, **kwargs)
    980 
    981 

~/.envs/dspy3/lib/python3.5/site-packages/gensim/models/deprecated/word2vec.py in load_old_word2vec(*args, **kwargs)
    151 
    152 def load_old_word2vec(*args, **kwargs):
--> 153     old_model = Word2Vec.load(*args, **kwargs)
    154     params = {
    155         'size': old_model.vector_size,

~/.envs/dspy3/lib/python3.5/site-packages/gensim/models/deprecated/word2vec.py in load(cls, *args, **kwargs)
   1614     @classmethod
   1615     def load(cls, *args, **kwargs):
-> 1616         model = super(Word2Vec, cls).load(*args, **kwargs)
   1617         # update older models
   1618         if hasattr(model, 'table'):

~/.envs/dspy3/lib/python3.5/site-packages/gensim/models/deprecated/old_saveload.py in load(cls, fname, mmap)
     85         compress, subname = SaveLoad._adapt_by_suffix(fname)
     86 
---> 87         obj = unpickle(fname)
     88         obj._load_specials(fname, mmap, compress, subname)
     89         logger.info("loaded %s", fname)

~/.envs/dspy3/lib/python3.5/site-packages/gensim/models/deprecated/old_saveload.py in unpickle(fname)
    378             b'gensim.models.wrappers.fasttext', b'gensim.models.deprecated.fasttext_wrapper')
    379         if sys.version_info > (3, 0):
--> 380             return _pickle.loads(file_bytes, encoding='latin1')
    381         else:
    382             return _pickle.loads(file_bytes)

AttributeError: Can't get attribute 'Word2VecKeyedVectors' on <module 'gensim.models.deprecated.keyedvectors' from '/Users/stps/.envs/dspy3/lib/python3.5/site-packages/gensim/models/deprecated/keyedvectors.py'>

Please paste or specifically describe the actual output or traceback. -->

#### Versions
Darwin-17.4.0-x86_64-i386-64bit
Python 3.5.2 (default, Jun 29 2016, 13:43:58)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
NumPy 1.14.1
SciPy 1.0.0
gensim 3.3.0
FAST_VERSION 0

**Comment by dotslash** [comment]
If it helps, this is exactly what i was doing.

https://github.com/dotslash/Ganymede/blob/ac9a852e716c79d03490845ba8113a13f32a5da4/fasttext_word_to_vec/playground-fb.fasttext-word2vec.ipynb

**Comment by menshikh-iv** [comment]
@dotslash all right, this shouldn't work, because `gensim.models.KeyedVectors.load_word2vec_format(model_file)` - is only word-vectors in word2vec format (this isn't a full w2v model, word2vec needs some additional matricies & parameters for training, that doesn't contain in `model_file`), for this reason, you can't load it.

**Comment by piskvorky** [comment]
It doesn't look all right to me. Why should Gensim store a model that it cannot load back?

Or do you mean @dotslash should load the model differently? (using a different class, such as `KeyedVectors.load` instead of `Word2Vec.load`?)

**Comment by menshikh-iv** [comment]
@piskvorky 
> Or do you mean @dotslash should load the model differently? (using a different class, such as KeyedVectors.load instead of Word2Vec.load?)

yes, user want to do `KeyedVectors.save` -> `Word2Vec.load`, this shouldn't work.

**Comment by piskvorky** [comment]
OK. The answer didn't make that clear to me. @dotslash does that solve your problem?

**Comment by akutuzov** [comment]
I also hit this problem and I also think it is weird that Gensim can't load the model it saved a minute ago :)
Once again, the situation is like this: 

1. We have a vector model stored in word2vec format (binary or text, does not matter)
2. We load it into Gensim using `gensim.models.KeyedVectors.load_word2vec_format`
3. Then we save it to the native Gensim format using `model.save` (one of the reasons to do that is that native Gensim models load MUCH faster) 
4. We try to load the saved model using `gensim.models.Word2Vec.load`.
5. The result is the error mentioned above: 
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'negative'
6. The expected result is, of course, that the model is loaded and can be queried for embeddings.

In fact it fails because the `load` method at https://github.com/RaRe-Technologies/gensim/blob/master/gensim/models/base_any2vec.py#L630 presupposes that the model it tries to load always has the `negative` and `trainables` attributes. But this is not the case for the ones saved from standard word2vec files.

As far as I can see this can be fixed by either:

1. modifying the `save` method so that it creates empty `negative` and `trainables` attributes before actually saving the model;
2.  or modifying the `load` method so that it checks for the existence of these attributes in the model and creates them if needed.

I am not sure what will be the preferred way to go in the context of the current redesigning of the whole vector framework in Gensim. But I can submit a PR for either of them :-)

**Comment by akutuzov** [comment]
Or at least Gensim should produce a warning is a user tries to use `models.Word2Vec.load` to load a model which lacks the necessary attributes. This warning can point the user to the `models.KeyedVectors.load` method.

**Comment by piskvorky** [comment]
@akutuzov the problem is saving an object of one class (`KeyedVectors`) and then trying to load from a different class (`Word2Vec`). That was never supposed to work, it's a mismatch. You might as well `LsiModel.save()` and then wonder why `Doc2Vec.load()` doesn't work.

The error message could better, though. If the unpickled object is not an instance of the class it was used on, which is easy to test, we could fail with a more explicit message. @menshikh-iv thoughts?

**Comment by menshikh-iv** [comment]
@piskvorky maybe write explicitly in error message that "`kv` isn't `w2v` (this is only one matrix with some metadata, for loading full `w2v` model please use `w2v.save` -> `w2v.load`)"

**Comment by piskvorky** [comment]
Yes, people for some reason think that the key-vectors are the same as a full model, but they're not. A better error message could help.
