### ISSUE TITLE
Need documentation about word2vec "# you can continue training with the loaded model!"

### ISSUE THREAD

**Issue by ttpro1995** [RaRe-Technologies/gensim#1967]
In documentation [models.word2vec](https://radimrehurek.com/gensim/models/word2vec.html), it said 
`model = Word2Vec.load(fname)  # you can continue training with the loaded model!`

However, I did not see any official document (with example) about this. 

There are a question on [stackoverflow](https://stackoverflow.com/questions/48443999/gensim-word2vec-continue-training-on-existing-model-attributeerror-word2ve/49185832#49185832)

```
# training_data: initial training data. contain list of tokenized sentences
model = Word2Vec(training_data, size=50, window=5, min_count=10, workers=4)
```

However, no matter what I put in total_examples, it worked (no error shown)  but I am not sure if it work correctly. 

As stackoverflow answer 

```
# datasmall: more sentences
# total_examples: number of additional sentence
# epochs: provide your current epochs. model.epochs is ok 
model.train(datasmall, total_examples=len(datasmall), epochs=model.epochs)
```

OR as doc in [word2vec.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py)

`model.train(datasmall, total_examples=model.corpus_count, epochs=model.epochs)`

**Comment by menshikh-iv** [comment]
Hello @ttpro1995 ,

> However, I did not see any official document (with example) about this

you extract this line from our documentation, what do you mean as "official document" in that case?
FYI - almost all of our models can be trained after loading (because we support online-learning).

`total_examples` is number of sentences, this used for logging proposes only, read carefully docstring for train method, need informaton already described https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.train

For this kind of questions, better to use [our mailing list](https://groups.google.com/forum/#!forum/gensim) instead of issue section of github.

**Comment by piskvorky** [comment]
I agree with @ttpro1995 that this is an issue: unclear documentation, no examples on how to continue training.

There probably should be an issue where we collect all such "missing or unclear pieces of documentation". Then this issue can be closed as "duplicate".
