### ISSUE TITLE
wikicorpus

### ISSUE THREAD

**Issue by numericlee** [RaRe-Technologies/gensim#2100]
see below

**Comment by numericlee** [comment]
in python3 over ubuntu

from gensim.corpora import WikiCorpus
wiki = WikiCorpus('enwiki-latest-pages-articles.xml.bz2') 


when the program encounters the WikiCorpus command, it shows a dialog box to kill the program. it does this 5 times. it is not clear after the 5 times whether it is continuing to run the program

![screenshot](https://user-images.githubusercontent.com/32748976/41745770-1b85b7ae-7576-11e8-9b41-e4f499cb1d8c.png)

**Comment by menshikh-iv** [comment]
Hm, this is because you run it with IDLE (this window produced by them) if you run it from the console - you'll have no any windows.

Related discussions
- https://stackoverflow.com/questions/38028151/how-do-i-get-rid-of-the-the-program-is-still-running-are-you-sure-you-want-to
- https://stackoverflow.com/questions/15557242/why-the-window-the-program-is-still-running-do-you-want-to-kill-it-during-deb
