### ISSUE TITLE
Why I got more docvec vectors than the number of my actual number of docs?

### ISSUE THREAD

**Issue by ruiatelsevier** [RaRe-Technologies/gensim#2120]
#### Description
I am using Doc2Vec to embed my docs into vectors, the training was successful but the results are strange to me. I have 46k docs, while the size of docvecs is 200k. I don't know what's wrong with my code.

#### Steps/Code/Corpus to Reproduce
```
class LabeledLineSentence(object):
    def __init__(self, doc_list, labels_list):
        self.labels_list = labels_list
        self.doc_list = doc_list
    def __iter__(self):
        for idx, doc in enumerate(self.doc_list):
              yield gensim.models.doc2vec.TaggedDocument(doc, [self.labels_list[idx]])


df = pd.read_csv("data/DATA_HADM.csv", escapechar='\\')
texts = df['text'].values  # this a ~46K array
label = list(df['id'])

size = 600 
it = LabeledLineSentence(texts, label)
    
model_d2v = Doc2Vec(min_count=10, window=5, vector_size=size, sample=1e-3, negative=5, workers=8)
model_d2v.build_vocab(it)
model_d2v.train(it, epochs=10, total_examples=model_d2v.corpus_count)
```

#### Expected Results
I expect the `model_d2v.docvecs` is a 46k-by-600 matrix.

#### Actual Results
The actual resulting matrix is a 200k-by-600 matrix, I don't understand.

#### Versions
Linux-4.4.0-1062-aws-x86_64-with-debian-stretch-sid
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0]
NumPy 1.14.3
SciPy 1.1.0
gensim 3.4.0
FAST_VERSION 1

**Comment by gojomo** [comment]
Issues here should be reserved for bugs-needing-fixes or feature requests - troubleshooting or questions are better served on the project discussion list: <https://groups.google.com/forum/#!forum/gensim>. That said, if you're using plain ints as your document IDs, and your highest document ID is int `200000`, then a 200000-slot array will be allocated, even if not all IDs are used. If you don't want this to happen, you should use string IDs (at a slight extra memory cost in remembering string-to-slot mapping, which shouldn't be a problem at your scale), or otherwise renumber your docs to have tags that start at int 0 and increment without gaps.
