### ISSUE TITLE
max_vocab_size is not what I expected when training Word2Vec

### ISSUE THREAD

**Issue by a-mustafa** [RaRe-Technologies/gensim#2131]
When I train word2vec model with **max_vocab_size=10,000** words, the number of unique vocabulary I get is only about **4,000 words** (measured using len(model.wv.vocab)). 

max_vocab_size is supposed to limit the number of unique words to the specified number (i.e., 10,000 in my case). It is possible to get less than the limit, if the number of words in the corpus is small. But my corpus can produce more words; **when I set max_vocab_size=None, I get 47,000 words**. 

Could you please help me understand the reason why I'm having only 4,000 unique words although max_vocab_size is much larger (10,000 words) and the number of unique words that my corpus can produce is about 47,000 words --with max_vocab_size=None.

- Note that I use: one worker, min_count=0, and NLTK Brown Corpus data for training.

- I observed the same behavior when I used other training data. 

#### Versions
Linux-4.4.0-87-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 
[GCC 5.4.0 20160609]
NumPy 1.14.3
SciPy 1.1.0
gensim 3.4.0
FAST_VERSION 1

Thanks,

**Comment by menshikh-iv** [comment]
@a-mustafa this is expected behavior, the current approach is heuristic, how it works:

After each input sentence (when you fill a vocab) current code executed
https://github.com/RaRe-Technologies/gensim/blob/4d921da6e34dc6c7c037ba1e4a36bf09ba56143d/gensim/models/word2vec.py#L1532-L1534

each time when filtering happens (i.e. vocab too large), we run filtering + increase `min_reduce` parameter (see https://radimrehurek.com/gensim/utils.html#gensim.utils.prune_vocab), this approach allow to do call filtering procedure non frequent (if we'll do it in "exact" manner, near `max_vocab_size`, we would run this procedure almost after every sentence without any changes (almost always) in vocab, because tokens distributed by https://en.wikipedia.org/wiki/Zipf%27s_law)

Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions (GitHub issues isn't suitable place for it)
