### ISSUE TITLE
Document pretrained word embeddings

### ISSUE THREAD

**Issue by lambdaofgod** [RaRe-Technologies/gensim#2310]
#### Description
Documentation doesn't seem to contain information on pretrained models - I can't find any information on them other than getting keys from 

`gensim.downloader.models.keys()`

Is there a reason to not contain this information in documentation?

If there is no such reason, then wouldn't it be beneficial to document these models?

I'd be happy to help with adding this information. But where should we put it?  I think [downloader documentation](**url**) would be the correct place.

**Comment by menshikh-iv** [comment]
@lambdaofgod 

> Is there a reason to not contain this information in documentation?

Yes, because this is really dynamic (independent repo) + all info stored in `gensim-data` repo (no reason to duplicate it). See https://radimrehurek.com/gensim/downloader.html for usage. 

> If there is no such reason, then wouldn't it be beneficial to document these models?

All additional information about models / datasets available through `.info()` or in https://github.com/RaRe-Technologies/gensim-data repository

**Comment by horpto** [comment]
@menshikh-iv Shouldn't `gensim.downloader` description have a link on `gensim-data` repo ?

And current  https://radimrehurek.com/gensim/downloader.html page has broken layout in the text nearly at the footer.
