### ISSUE TITLE
Problem while passing wlocal function in tfidf model 

### ISSUE THREAD

**Issue by xmedved1** [RaRe-Technologies/gensim#2444]
#### Problem description
I tried to use math.sqrt function on term frequency when computing TF-IDF model as you declare in script documentation:

```
wlocals : function, optional
            Function for local weighting, default for `wlocal` is :func:`~gensim.utils.identity`
            (other options: :func:`math.sqrt`, :func:`math.log1p`, etc).
```
========================================
Gensim implementation:

```python
tf_array = self.wlocal(np.array(tf_array))
vector = [
   (termid, tf * self.idfs.get(termid))
   for termid, tf in zip(termid_array, tf_array) if abs(self.idfs.get(termid, 0.0)) > self.eps
]
```

Error:

```
  File "/home/xmedved1/.local/lib/python3.6/site-packages/gensim/models/tfidfmodel.py", line 432, in __getitem__
    tf_array = self.wlocal(np.array(tf_array))
TypeError: only size-1 arrays can be converted to Python scalars
```
======================================

Fix if I want to use  math.sqrt:

```python
tf_array = np.array(tf_array)
vector = [
    (termid, self.wlocal(tf) * self.idfs.get(termid))
    for termid, tf in zip(termid_array, tf_array) if abs(self.idfs.get(termid, 0.0)) > self.eps
]
```

==========================================
gensim version 3.7.2

==========================================
I don't know if this is a problem to fix, because in Gensim implementation I can do some normalization that includes all items in list (something like tf = n_i_j / sum(n_k_j) where i,k is token and i!=k and j is the document  –> this is not allowed in my fix). So I thing the problem is the documentation of wlocal parameter.

Best regards M

**Comment by piskvorky** [comment]
@Witiko could you please have a look? Many thanks.

**Comment by Witiko** [comment]
@piskvorky This appears to be a regression from 0bfb9daa540308cca9663bdf66a6266d599cf8ed, which is part of PR #1791. Since this commit, `wlocal` has been applied on the entire numpy array of term frequencies rather than the individual term frequencies. A straightforward way to regain the original behaviour would be to use [`numpy.vectorize`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html).

**Comment by piskvorky** [comment]
I don't really understand what that means, what are these corners @xmedved1 pointed out. Can you suggest a fix to the documentation (+a unit test to capture any future regressions), if this is indeed a problem with documentation? CC @markroxor as author of #1791.

TFIDF is a simple model, I'm strongly -1 on introducing any bloat or complexity that obscures its basic use-cases because of some obscure useful-maybe-if options.

**Comment by Witiko** [comment]
@xmedved1's fix and changing `tf_array = self.wlocal(np.array(tf_array))` to `tf_array = np.vectorize(self.wlocal)(np.array(tf_array))` are equivalent, although mine makes fewer changes. However, the SMART implementation from #1791 assumes that `wlocal` accepts numpy arrays, not individual frequencies (see the [`smartirs_wlocal` function](https://github.com/RaRe-Technologies/gensim/blob/30528a5c01de9c2eb0b2f4d5cf7351adace369d1/gensim/models/tfidfmodel.py#L154)), so this would require a larger rewrite.

I am inclined to agree with @xmedved1 that it would be better to document this rather than fix this, since a `wlocal` function benefits from access to the entire term frequency vector rather than just a single term frequency (see the [`smartirs_wlocal` function](https://github.com/RaRe-Technologies/gensim/blob/30528a5c01de9c2eb0b2f4d5cf7351adace369d1/gensim/models/tfidfmodel.py#L154)).

As for the update of the documentation, changing the current text:

```
        wlocals : function, optional
            Function for local weighting, default for `wlocal` is :func:`~gensim.utils.identity`
            (other options: :func:`math.sqrt`, :func:`math.log1p`, etc).
```

to the following:

```
        wlocal : function, optional
            Function for local weighting, default for `wlocal` is :func:`~gensim.utils.identity`
            (other options: :func:`numpy.sqrt`, :func:`numpy.log1p`, etc).
```

should clear any misunderstanding. However, it can be considered a breaking change.

**Comment by piskvorky** [comment]
Reading that as a user, that documentation update (math => numpy) still doesn't tell me much.

Can make the documented API contract stronger? Especially if it potentially breaks some of the code somewhere else (`smartirs` something).

**Comment by Witiko** [comment]
> Reading that as a user, that documentation update (math => numpy) still doesn't tell me much. What should my own function look like?

Perhaps we can show one of the SMART functions as an example:

```
wlocal : function, optional

Function for local weighting, default for `wlocal` is :func:`~gensim.utils.identity`
(other options: :func:`numpy.sqrt`, `lambda tf: 0.5 + (0.5 * tf / tf.max())`, etc.).
```

> @xmedved1 @Witiko Can make the documented API contract stronger? Especially if it potentially breaks code somewhere else (`smartirs` something).

Currently, `wlocal` is a numpy.array -> iterable function. We can make this contract explicit by putting it into the documentation.

**Comment by piskvorky** [comment]
Good practical examples are definitely preferable to (though not precluding) complex type descriptions. My view here is entirely pragmatic: I don't understand myself how I should to make use of this functionality. Perhaps this even hints at a missing tutorial / example usage section (focus on motivation and context, not just types), rather than just extending a function docstring here and there.

More tests are always welcome, yes. Thanks.
