### ISSUE TITLE
Passing nonsense (int) for `corpus_file` generates confusing OSError in get_offsets_and_start_doctags_for_corpusfile

### ISSUE THREAD

**Issue by baidik1** [RaRe-Technologies/gensim#2460]
#### Problem description

I am trying to train a doc2vec model over 1.35 million docs. Each line of the opened file corresponds to a doc and I am creating a TaggedDocument object from that. I am getting these errors which I cannot resolve. Note that the 1351747 below corresponds to the number of docs.
```
OSError: [Errno 9] Bad file descriptor: 1351747
```

This is my code:
```python
taggeddoc = []
f = open('EnglishT.txt')
for line in f:
    td = TaggedDocument(gensim.utils.to_unicode(str.encode(line)).split(),[str(index)])
    taggeddoc.append(td)
    index += 1
f.close()
print(len(taggeddoc))
model = gensim.models.doc2vec.Doc2Vec(vector_size=50, dm=0, dbow_words=0, workers=30, alpha=0.025, min_alpha=0.025)

model.build_vocab(taggeddoc)
# start training
for epoch in range(500):
    model.train(taggeddoc, model.corpus_count, epochs=model.iter)
    model.alpha -= 0.002  
    model.min_alpha = model.alpha 
```

Using Python3:
```
Traceback (most recent call last):
  File "en_d2v.py", line 25, in <module>
    model.train(taggeddoc, model.corpus_count, epochs=model.iter)
  File "/home/junlp/.local/lib/python3.6/site-packages/gensim/models/doc2vec.py", line 799, in train
    offsets, start_doctags = self._get_offsets_and_start_doctags_for_corpusfile(corpus_file, self.workers)
  File "/home/junlp/.local/lib/python3.6/site-packages/gensim/models/doc2vec.py", line 828, in _get_offsets_and_start_doctags_for_corpusfile
    corpus_file_size = os.path.getsize(corpus_file)
  File "/usr/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [Errno 9] Bad file descriptor: 1351747
```

Using Python2
```
Traceback (most recent call last):
  File "en_d2v.py", line 32, in <module>
    model.train(taggeddoc, model.corpus_count, epochs=model.iter)
  File "/home/junlp/.local/lib/python2.7/site-packages/gensim/models/doc2vec.py", line 799, in train
    offsets, start_doctags = self._get_offsets_and_start_doctags_for_corpusfile(corpus_file, self.workers)
  File "/home/junlp/.local/lib/python2.7/site-packages/gensim/models/doc2vec.py", line 828, in _get_offsets_and_start_doctags_for_corpusfile
    corpus_file_size = os.path.getsize(corpus_file)
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
TypeError: coercing to Unicode: need string or buffer, int found
```

#### Versions

Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
('Python', '2.7.15rc1 (default, Nov 12 2018, 14:31:15) \n[GCC 7.3.0]') 
('NumPy', '1.16.2')
('SciPy', '1.2.1')
No handlers could be found for logger "smart_open.ssh"
('gensim', '3.7.2')
('FAST_VERSION', 1)

For Python3,
Python 3.6.7 (default, Oct 22 2018, 11:32:17)

**Comment by gojomo** [comment]
This sort of troubleshooting should be handled via the discussion list, https://groups.google.com/forum/#!forum/gensim , rather than a Github issue, unless it's clear that a bug or required new feature is involved. 

Your code seems based on an outdated/bad example, in a couple ways. In particular, the 2nd positional argument you've provided to `train()`, `model.corpus_count`, is actually binding to a `corpus_file` parameter (added in recent gensim versions). Explicitly naming the intended parameter, `train(taggeddoc, total_examples=model.corpus_count, epochs=model.iter)`, should resolve this problem. 

But separately: it's rare for any user to need to call `train()` multiple times in a loop. (It's unnecessary and prone to other errors, such as decrementing `alpha` in destructive way, as has also happened here.)  Leave the default `alpha`/`min_alpha` in place, call `train()` once with your preferred `epochs` value, and it will do the right thing.

**Comment by baidik1** [comment]
@gojomo Thanks for your help. I made the necessary changes, and cleaned up the code. Closing this.

**Comment by gojomo** [comment]
Reopening with new name to address issue that passing an obviously-bad `corpus_file` value generated such an unhelpful error.

**Comment by saraswatmks** [comment]
Hi @gojomo If no one is working on this, can I take this up ?

**Comment by gojomo** [comment]
@saraswatmks of course!

**Comment by saraswatmks** [comment]
@gojomo Thanks, I am on it. Incase, I need some clarifications I can ask here, right?

**Comment by gojomo** [comment]
@saraswatmks of course!
