### ISSUE TITLE
gensim.similarities.Similarity merges results from shards incorrectly (LSI model)

### ISSUE THREAD

**Issue by avoskresensky** [RaRe-Technologies/gensim#2584]
If "num_best" is used, `gensim.similarities.Similarity` runs the query against each of the shards (MatrixSimilarity objects) and then merges the results.

MatrixSimilarity uses `matutils.full2sparse_clipped()` to pick "num_best" results which sorts by the absolute value.

gensim.similarities.Similarity on the other hand, just uses `heapq.nlargest` (in `__getitem__`) to merge the results from each of the shards. So negative sims are either pushed down the list or cut off completely.

**Comment by piskvorky** [comment]
You're right. This seems an inconsistency / bug introduced by PR #811.

@avoskresensky in your use case – is `abs` desirable, or is the raw similarity desirable?

**Comment by piskvorky** [comment]
Negative values (close to -1) mean "opposite vectors", which is can also be interpreted as "very similar", because it indicates a semantic connection between the two inputs. Values around 0.0 are perpendicular = unrelated.

Whether "opposite" really means "similar" or not will depend on how you generated your vectors, and what you're using them for. That's why I ask: this is an "upstream" question, not a technical one.

Either way: can you open a PR that fixes Similarity to sort on `abs` values as well? Cheers.

**Comment by mpenkov** [comment]
@avoskresensky Ping on this. Are you able to make a PR?

**Comment by avoskresensky** [comment]
Not in the next couple of weeks.
