### ISSUE TITLE
Using gensim Doc2Vec for vectorizing documents of varying sizes

### ISSUE THREAD

**Issue by arshad171** [RaRe-Technologies/gensim#2704]
I have tried implementing Doc2Vec on datasets consisting of similar document sizes (of about 300 words), and Doc2Vec performs really well as long as the data I provide during evaluation is similar in size compared to the docs on which the model was trained on (300 words).

But I also wanted to train the model on datasets where the doc size has a lot of variance (20 - 1000 words), and I feel that training the model on such a dataset would not produce good results as the documents that have lesser number of words like 20 or so would have provide lesser features and have lesser influence on the model, when compared to the docs with 1000 words in the same dataset.

I'm not sure if this understanding of mine is right.

Hence, one workaround which I thought of is, to train multiple models for fixed doc lengths (with some buffer).
i.e.

| model | doc-size range |
| -------- | -------------------- |
| model_1 | 20 - 150 |
| model_2 | 150-500 |
| model_3 | 500-1000 |

And after the model is deployed, vectorize new docs based on their lenghts.

I'm not sure if this is a good approach, or if there is a better way of achieving the goal.

**Comment by gojomo** [comment]
Questions/discussion should generally go to the project discussion list – https://groups.google.com/forum/#!forum/gensim – reserving this issue-tracker for bug-reports & feature-requests.

Only trying your approach could tell if it's worthwhile... and the things you try should be driven by any actual deficiencies you might be able to measure when using mixed-length docs (rather than an unquantified sense it might not work).  

You could also try equalizing the influence of smaller documents by repeating them - either repeating the entire document, or padding the document with its own repeated words – to potentially ensure their influence isn't outweighed by larger docs. You could also try breaking larger docs into subunits, like paragraphs or simply some standard-sized chunk-of-words – to put all docs on equal footing, and return results that target not just docs but portions of docs.

**Comment by mpenkov** [comment]
@arshad171 Please move this discussion to the mailing list as @gojomo suggested. Closing here.
