### ISSUE TITLE
RFC: New website design

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#2927]
I've hired a designer to redesign the Gensim website, give it a more modern & unified look for our 4.0 release.

I asked them to keep the same content + structure = static "plain HTML" pages for the "outside" website, plus auto-generated docs for the "inside" API ref. Just looking better than the current https://radimrehurek.com/gensim/.

The designer came up with the following options. They are generic templates, to be customized and filled with content, so it's only about the general look&feel at this point.

### "Outside" pages

* http://be.beantownthemes.com/html/index-erp2.html
* http://be.beantownthemes.com/html/content/electronics/contact.html
* http://be.beantownthemes.com/html/index-landing2.html
* http://be.beantownthemes.com/html/index-app4.html
* http://be.beantownthemes.com/html/index-mechanic4.html
* http://be.beantownthemes.com/html/index-pay2.html
* http://preview.themeforest.net/item/saasbox-multipurpose-html-template-for-saas/full_screen_preview/25607146
* https://preview.themeforest.net/item/jumpstart-app-and-software-template/full_screen_preview/24207799
* http://preview.themeforest.net/item/landrick-responsive-saas-and-software-template/full_screen_preview/24438577

### "Inner" API reference pages

* https://sphinx-rtd-theme.readthedocs.io/en/stable/
* http://docs.guzzlephp.org/en/stable/
* https://bashtage.github.io/sphinx-material/

@gojomo @mpenkov any preference? Your input and comments are welcome. Otherwise I'll go ahead and pick something, not critical. Cheers.

**Comment by piskvorky** [comment]
…my preference is large fonts, static content (nothing jumping/moving) and lots of air/space. So these three:

* https://preview.themeforest.net/item/jumpstart-app-and-software-template/full_screen_preview/24207799
* http://preview.themeforest.net/item/saasbox-multipurpose-html-template-for-saas/full_screen_preview/25607146
* http://be.beantownthemes.com/html/index-erp2.html

And for API docs, the recognizable https://sphinx-rtd-theme.readthedocs.io/en/stable/ .

**Comment by mpenkov** [comment]
Had a look, I agree with your picks and the readthedocs scheme.

**Comment by piskvorky** [comment]
@mpenkov @gojomo close-to-finish draft:
https://stage.friendlystudio.cz/gensim-doc

Any comments, suggestions? Now is the right time :)

Things that will still change:

* Update [logo](https://drive.google.com/drive/folders/0B0oGRkbSoq_3UnUxSXZ0dnkyUkE?usp=sharing) + fix the tooltip on logo hover.
* Fix the "main image" / code sample on top
* Fix a few images + typo.

Otherwise the site structure, layout and content are complete. The switch should not require any changes to our deployment process: it's still static HTML generated by Sphinx.

**Comment by gojomo** [comment]
One key functional comment: On my retina MBP16", in Brave with page zoom at default, and browser width about 3/4 of my screen, the header navigations links ('Home Documentation Support API About`) were folded into the hamburger-menu. That made me think they were an inconvenient extra click away, until I noticed them appear when trying a smaller font. I'd suggest ensuring that the header links appear on any viewport that's 1024px or wider - so that it's only on truly mobile/constrained browsers that the drop-down menu is required. 

Overall it looks very nice & the having the docs in a familiar read-the-docs layout, with permanent navigation links in the left margin, will be very beneficial.

If anything, the overall style/spacing of the main landing page may be a bit *too* slick, giving strong impression of a subscription SaaS product sales pitch for end-users, rather than a library for developers. This extends to some of the wording: "Try now for free" sounds like some sort of time-limited signup, rather than forever-free open-source. I tend to expect open-source stuff to be a bit more spartan, info-dense, and even rough-around-the-edges. For more info-density & 'developer feel' I'd suggest:

* shrinking giant main title "gensim: topic modelling for humans" from full screen to just a header
* eliminating the 'dashboard' graphic unless/until it's a highly-relevant image
* at this point, 'explore all features' button to scroll-jump down probably isn't necessary, as the list-of-features will already begin on-screen above-the-fold
* eliminate redundant [orange] 'features' [big blue] 'Features of gensim phyton library' dual-headers in favor of one smaller 'features' - also note 'phyton' typo
* standardize whether 'gensim' is capitalized or not when mid-sentence - varies across page
* generally shrink fonts a bit to get more on screen at once
* include better-labelled links to both PyPI page & Github project. For example, a 'download now' link isn't exactly the right 'call-to-action' for either casual library users or code-hackers, who'd be more likely to want a more prominent link to 'install' (or 'installation instructions' ) or to 'github project page'
* replacing the placeholder contact-icons for things like FB/Instagram/GooglePlus with working icons to Github/Gitter/GoogleGroups

For the docs:
* It seems we have no "how to install" section in the docs - thus the 'download now' link just goes to the PyPI page. But such a page recommending `pip install gensim` for most cases, recommending the use of a virtual environment, alluding to the popular `conda` option, & mentionig some common pitfalls/workarounds could head off some support issues, and provide a key docs entry point from either the landing-page or other places where we or others recommend gensim
* is there a plan to keep more than one version of the autogenerated docs up? many projects do, with cross-version navigation links & top-of-page warnings when looking at older docs – and some big version transitions (including upcoming 3.8.3 to 4.0.0) may benefit from keeping both sets of docs up

Finally, it'd be good if the landing page had some dedicated, near-the-top line for "latest news" and/or "latest release" - typically just a dated link of the form "Latest: gensim-X-Y-Z released, 2020-MM-DD" to the mailing-list-post or github-page detailing the most-recent release.

**Comment by piskvorky** [comment]
I'd like to keep several versions (releases) in the navigation. Not sure how to do it with Sphinx, but I saw it in other projects, should be possible.

All good points (except shrinking fonts), I'll pass it on to the web devs. Thanks!

**Comment by mpenkov** [comment]
No comments from me, other than it looks good!
