### ISSUE TITLE
Cannot load pretrained Doc2Vec: AttributeError: Can't get attribute 'DocvecsArray' on <module 'gensim.models.doc2vec'

### ISSUE THREAD

**Issue by muhlbach** [RaRe-Technologies/gensim#3110]
#### Problem description

I'm trying to load a pre-trained Doc2Vec model from this [https://github.com/jhlau/doc2vec](https://github.com/jhlau/doc2vec) 

#### Steps/code/corpus to reproduce

`
from gensim.models.doc2vec import Doc2Vec;
model = Doc2Vec.load("enwiki_dbow/doc2vec.bin")
`

This throws the following error:

`AttributeError: Can't get attribute 'DocvecsArray' on <module 'gensim.models.doc2vec' from 'PATH_TO_VIRTUAL_ENVIRONMENT/lib/python3.8/site-packages/gensim/models/doc2vec.py'>
`
#### Versions

As requested:

```python
macOS-10.16-x86_64-i386-64bit
Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ]
Bits 64
NumPy 1.18.5
SciPy 1.6.2
gensim 4.0.1
FAST_VERSION 1
```

**Comment by gojomo** [comment]
As noted on that page's 'Requirements' section:

> * Gensim: Best to use my forked version of gensim; the latest gensim has changed its Doc2Vec methods a little and so would not load the pre-trained models.

Specifically: those were created with, and can only be loaded into, a nonstandard Gensim fork that diverged about 5 years ago. You wouldn't be able to load them into either an official Gensim release of the same era (v `0.12.4`), or the much-later current version of Gensim (`4.0.1`).

You will likely want to train your own model with the latest Gensim.

**Comment by mb1069** [comment]
I've managed to load that embedding with the official gensim==3.8.3

**Comment by gojomo** [comment]
Even with success *loading* a 7yo `Doc2Vec` model from <https://github.com/jhlau/doc2vec> into a 3yo version of Gensim, I'd be wary of relying on that combination's results as a basis for analyze or working with any more-current data, compared to, say, training one's own model on relevant data.

Language senses continue to drift, important new terms arrive, & Gensim's received a lot of fixes & optimizations. 

But also, the "English Wikipedia DBOW (1.4GB)" model supplied there is suspiciously-tiny for what it purports to provide. The accompanying scripts imply they're training models with 300-dimensional vector. A Wikipedia dump of the era would've had at least 3M articles.

So the result model of such a DBOW training run would usually include at least 3M 300d `float` vectors learned for each article title. That alone would be (`3,000,000 vectors * 300 dimensions * 4 bytes/dimension`) 3.6GB in size, even *without* word-vectors, internal model-weights, vocabulary info, etc. So that 1.4GB model must be quite restricted in ways unclear from surrounding text.
