### ISSUE TITLE
Enable to master the window size variations during training

### ISSUE THREAD

**Issue by M-Demay** [RaRe-Technologies/gensim#3159]
**Context:** I am trying to use `gensim` on a corpus in which the order of words has no importance at all. So my idea is to give the constructor of the class `Word2Vec` a large window size, so that it trains each word with the full rest of the sentence (the iterable I give as parameter `sentences` to the `Word2Vec` constructor yields sentences in which word order is irrelevant).

I noticed [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec_inner.pyx#L572) in the code that during training, the window size was reduced of a size drawn uniformly at random. If I get it right, it feels like saying, if words are too far from one another, sometimes they carry less sense together. And at any rate, adding some randomness very often gives better results in machine learning in general. In general I agree with these two ideas.
- However, I find it too bad that this is hard-coded, and that the user cannot choose to keep the window fix-sized, with the size they enter. 
-  Another cool option would be to be able to input a minimal and a maximal size, instead of the current behaviour where the window size varies from the full length provided by the user to 0.

**Propositions:**
 From these observations I propose to do one or all of the following changes:
- Add a parameter to choose whether or not the window size randomly reduces. This could be something like `change_window_size`, set to `True` by default to be consistent with the current behaviour. 
- Add parameters for lower and higher bounds of the final window size. Note that if these bounds are equal, this amounts to no random reduction at all and this replaces the behaviour of the previous proposition.
- [Bonus] We could also imagine that instead of drawing sizes uniformly at random, the user could choose the probability distribution. But this is more of an idea I'm throwing into the air, rather than one I'm ready to implement right now. I don't know if it is relevant enough, considering the code changes it may imply.

What do you think of this ? If you're ok with it, I plan on doing the modifications myself.

**Comment by gojomo** [comment]
This request comes up from time-to-time, or other variants for customizing the window behavior - assymetric or 1-way windows (#1600, #2172), or other influence/sampling weights per position (#2114 or the learned-weighting of @Witiko in #2840).

As you've noted, setting a very-large window, where nearly every random draw will be larger than your actual texts, should approximate a 'whole text' window fairly well. (For example, given the 10,000-token implementation limit, setting `window` to `2^30` would mean less than 1-in-a-million training windows are ever smaller than 10,)000.

Still, I'd welcome a way to make this more configurable, given how often it's requested, if it was of minimial API/performance impact. (For people who want their whole window used each time, the generation of the random windows is an unnecessary calculation - for exaple, at https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec_inner.pyx#L573 & https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec_inner.pyx#L669). WDYT, @piskvorky ?

In keeping with the existing naming of the behavior in the source code, I'd name a flag to turn this on/off as `reduced_windows`, default `True` (as traditional in word2vec/etc). 

While the idea of a min/max window would achieve the goal, I'm not sure there are any needs for a higher min other than min=max, and such flexibility might make the code less clear for a wholly-theoretically need. Similarly, other weightings/distribution options could be considered if there were experimental results that they offer big wins, but otherwise, the non-standard complication would be hard to justify.

**Comment by piskvorky** [comment]
It makes sense to me, but I worry the (optimized) code paths are already convoluted enough. Adding another param would need to be done with care – easy to miss some code path, apply it inconsistently across the already existing param combinations: `corpus_file`, `skip gram`, `negative sampling`… at least we got rid of the Python code paths already!

**Comment by gojomo** [comment]
FWIW, the reason the `reduced_windows` values are done in a batch here is that in an earlier version, of generating a reduced window each loop through, my profiling showed a lot of time doing that - a batch per text gave a noticeable speedup. There's likely potential for further optimization here, perhaps via an even-faster PRNG or reuse of some rarely-refreshed buffer of values, etc - that's still good enough for the totally-non-adversarial variety needed here.
