### ISSUE TITLE
Complete triage of PRs for version 4.1.0

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3200]
Gentlemen, there are 6 in-progress PRs that I initially marked for inclusion into the 4.1.0 release [here](https://github.com/RaRe-Technologies/gensim/projects/9).

I propose that we deal with them after the release, as they do not appear to be critical, and need not hold back the release. Can you please have a look at let me know?

**Comment by piskvorky** [comment]
I don't see anything under that link. Wrong URL?

**Comment by mpenkov** [comment]
Hmm, works for me. Maybe github is having some sort of glitch.

Another way to get to it is to go to https://github.com/RaRe-Technologies/gensim/projects and click on the first project in the list (PR triage 2021-06).

**Comment by piskvorky** [comment]
Yes, it loads now. Weird.

By "in-progress", you mean the "Needs work before merge" column, right?

If so, the only PR worth considering as "urgent" (to be included in 4.1.0) is https://github.com/RaRe-Technologies/gensim/pull/3000. That's because it changes / cleans up the API, and these things are always better done sooner rather than later.

**Comment by mpenkov** [comment]
OK, I'll push #3000 over the line, and then after we complete #3199 we can initiate the release.
