### ISSUE TITLE
simple_processing() str_iterator issue

### ISSUE THREAD

**Issue by harish2sista** [RaRe-Technologies/gensim#3480]
Hi, 
I'm trying to convert a list of text data into tokens, I am using the simple_processing() function and I got the following error. 

input function:
```
def sent_to_words(sentences):
    for sentence in sentences:
        yield(gensim.utils.simple_preprocess(str(sentence), deacc=True))
```

Error output: 
```
result = ''.join(ch for ch in norm if unicodedata.category(ch) != 'Mn')
TypeError: category() argument must be a unicode character, not str_iterator
```

Can someone tell me how to fix this bug?

**Comment by harish2sista** [comment]
After restarting and running again, I got the following error. 

`SystemError: error return without exception set`

**Comment by gojomo** [comment]
This issue tracker is best-used for reporting bugs or feature-requests, rather than working through usage issues. Either the Gensim project's discussion forum, https://groups.google.com/g/gensim , or StackOverflow are better places to ask for help working through errors in your usage. (Only if you're highly confident you've hit a bug in the library's code, & can describe a reliable complete way to trigger it, should such an error be reported as an issue here.)

That said:

* If `sentence` is already a proper text string proper to send to `simple_preprocess()`, it shouldn't be necessary to apply `str()` to it. On the other hand, if it's *not* already a string, using `str()` may add unwanted extra Python-representation characters. So it's only needed (to force the right type) in exactly the cases where it likely does unintended/unwanted things.
* The `TypeError` implies you're passing something other than a plain string into `simple_preprocess()`. (Does that error really come from exactly the code shown above, or other code?) The `SystemError` has too little context to understand if it's related to your original question at all.

If you're still facing a problem, ask again in one of the more-appropriate places mentioned above, and be sure to also include:

* the exact code that triggers the error, including showing what `sentences` variable contains - ideally, actual data (synthetic if necessary) sufficient to trigger the same error you're getting, every time you try
* the *entire* error messages you see, including any 'traceback' info identifying individual involved lines-of-code, & filenames, & order-of-calls – this best helps answerers to be sure of how the problem-line/error is being reached

Closing here but if I see an expanded question those other places will be happy to provide more pointers.

**Comment by harish2sista** [comment]
Hey, Thanks for the help. The system error does not have anything to do with the gensim library. I think some of my Ubuntu OS C-library files got corrupted during the software update. The reinstallation of the OS fixed the issue for me.
