### ISSUE TITLE
word2vec: Using google news vectors for online training

### ISSUE THREAD

**Issue by ankeshanand** [RaRe-Technologies/gensim#775]
I need to perform some online training on top of a pre-trained word vectors. I was planning to use the Google News vectors but it's available in the binary format and according to http://rare-technologies.com/word2vec-tutorial/, I can't use the `load_word2vec_format()`. 

Is there any other way to build a model with pre-trained vectors and then perform online earning over more sentences?

Note: For online training, I am planning to use the fork mentioned here: http://rutumulkar.com/blog/2015/word2vec/

**Comment by ankeshanand** [comment]
Bumping the issue.

**Comment by gojomo** [comment]
Gensim's Word2Vec class will load vectors from the Google tool, including the 3M GoogleNews vectors, just fine. Just supply `binary=True`. 

However, `load_word2vec_format()` does not proper initialize the model for further training, as that vector format doesn't include other data (such as word frequencies or the NN hidden-to-output weights) needed for a still-trainable model. 

You can search the project discussion list (https://groups.google.com/forum/#!forum/gensim) for prior discussion of similar needs; in particular there's an (experimental) `intersect_word2vec_format()` method that can be used to merge common words from an outside source with a vocabulary built from your own corpus, and from that point continue training. 

However, this is all murky territory. Lots of people want to do this, some have, but I haven't seen any writeups describing strong results or guidelines for deciding all the necessary tradeoffs. My hunch is that the 'translation matrix' approach – as described in the wishlist page https://github.com/RaRe-Technologies/gensim/wiki/Word2Vec-&-Doc2Vec-Wishlist#implement-translation-matrix-of-exploiting-similarities-among-languages-for-machine-translation – may both be faster and give better results. (The 'Skip-Thoughts' paper uses that approach to extend their own corpus' limited vocabulary with words from elsewhere... rather than forcing their new words into the full vocabulary from elsewhere.)

**Comment by tmylk** [comment]
Closing as resolved.
