### ISSUE TITLE
Distributed LDA raises exception

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#82]
Reported by Romain here http://groups.google.com/group/gensim/browse_thread/thread/c824cc3777c05a47 :

```
2012-03-19 16:05:05,937 : ERROR : failed to initialize distributed LDA 
(cannot connect: [Errno 22] Invalid argument) 
Traceback (most recent call last): 
  File "lda_gensim.py", line 12, in <module> 
    lda = gensim.models.ldamodel.LdaModel(corpus=mm, id2word=id2word, 
num_topics=200, distributed=True) 
  File "/usr/local/lib/python2.6/dist-packages/gensim-0.8.4-py2.6.egg/ 
gensim/models/ldamodel.py", line 255, in __init__ 
    raise RuntimeError("failed to initialize distributed LDA (%s)" % 
err) 
RuntimeError: failed to initialize distributed LDA (cannot connect: 
[Errno 22] Invalid argument) 
I carefully followed the instructions, set up a Pyro name server, 
started with 2 workers and a dispatcher on the same machine. 
I also tried with LSI and it gives me the same error. 
I first followed the tutorial with Wikipedia, I prepared the corpus 
and everything seems to be ok. 
I also successfully installed the latest version of Pyro4, numpy and 
scipy with easy_install. 

gensim : 0.8.4 
numpy : 1.3.0 
scipy : 0.7.0 
pyro4 : 4.12 
```

**Comment by sytpp** [comment]
Hello, 
I am having problems running the distributed version of gensim on my Mac Book Air (which should allow at least for distribution in two). I assume since it is one an the same machine, I am not setting up a worker and a dispatcher explicitly but simply set  "distributed=True" in the ldaModel function. However, I encounter this error:

  File "build_model_distributed.py", line 48, in <module>
    lda = gensim.models.ldamodel.LdaModel(corpus=corpus_tfidf, id2word=dictionary, num_topics=50, passes=30, distributed=True)
  File "/usr/local/lib/python2.7/site-packages/gensim-0.12.1-py2.7-macosx-10.10-x86_64.egg/gensim/models/ldamodel.py", line 305, in __init__
    raise RuntimeError("failed to initialize distributed LDA (%s)" % err)
RuntimeError: failed to initialize distributed LDA (Failed to locate the nameserver)

I am using Pyro version: 4.40 and Python 2.7.10.

Thanks for your help!

**Comment by tmylk** [comment]
@sytpp The fastest LDA on a single box is the Multicore version. Would it work for your use case? https://github.com/piskvorky/gensim/blob/master/gensim/models/ldamulticore.py

**Comment by sytpp** [comment]
@tmylk for the moment I am just running it on my Mac Book but it would be nice to later be able to scale up ...

**Comment by tmylk** [comment]
@sytpp  Even on a single macbook air this tutorial should speed things up
http://rare-technologies.com/multicore-lda-in-python-from-over-night-to-over-lunch/
