### ISSUE TITLE
Segmentation fault when creating a Word2Vec model.

### ISSUE THREAD

**Issue by AritzBi** [RaRe-Technologies/gensim#896]
Hi!

I am creating a Word2Vec model using gensim and after few minutes, the program crashes and returns a segmentation fault.  Is there any log where I can check what is happening? The same source code is working properly in other computers.

**Comment by tmylk** [comment]
Hi,

How is logging configured? Is it something along these lines?

```python
logging.basicConfig(
        format='%(asctime)s : %(threadName)s : %(levelname)s : %(message)s',
        level=logging.DEBUG) 
```

**Comment by AritzBi** [comment]
Yep.

"""2016-09-28 17:22:07,320 : DEBUG : queueing job #6901 (9891 words, 84 sentences) at alpha 0.02481
2016-09-28 17:22:07,331 : DEBUG : queueing job #6902 (9893 words, 57 sentences) at alpha 0.02481
2016-09-28 17:22:07,346 : DEBUG : queueing job #6903 (9556 words, 90 sentences) at alpha 0.02481
2016-09-28 17:22:07,359 : DEBUG : queueing job #6904 (9881 words, 43 sentences) at alpha 0.02481
2016-09-28 17:22:07,370 : DEBUG : queueing job #6905 (9528 words, 48 sentences) at alpha 0.02481
[1]+ Segmentation fault (core dumped)  nohup python text_to_word2vec.py complete.text complete
"""

**Comment by gojomo** [comment]
Does it always happen at exact 'same place'? How about if running with a different number of worker threads (including just 1)?

What Python version and how were Python, gensim, and supporting libraries installed? 

What OS and what memory-usage is shown by the OS tools during running and leading up to the error?

**Comment by AritzBi** [comment]
No, sometimes occurs at the beginning, other times after some minutes. I've tried with 1 and 4 workers and the same problem happens.

Python: 2.7.12
Gensim: 0.13.2
scipy: 1.10.0
Cython: 0.24.1
numpy: 1.11.1

Ubuntu 16.04.1. 

Before the error the memory usage was around 2GB.

**Comment by gojomo** [comment]
(Is that an accurate scipy version? That'd be quite old compared to the other packages listed.)

The issue is probably some aspect of your machine or configuration outside of gensim. Most of what gensim does is in interpreted Python that (even when buggy) won't likely cause segmentation faults; the raw-memory accesses (in the optimized cython code) could theoretically trigger such errors – but are pretty straightforward & well-tested, without causing such reliable errors in many other users' configurations. 

The best I can suggest in such a situation is to try in a fresh environment (or perhaps even fresh machine), as for example via the rebuild-a-minimal-setup from scratch approach described in a forum thread: https://groups.google.com/d/msg/gensim/AjoAwmnnxiM/wnClJceUCAAJ

**Comment by tmylk** [comment]
@AritzBi Have you tried it in a fresh env?

**Comment by AritzBi** [comment]
@tmylk I've tried to launch again the process in a fresh virtual environment but the problem persists. Right now I can't format the machine but I can re-install dependencies. Which ones should I try to update or rebuild?

**Comment by tmylk** [comment]
Do you have same dependencies on all the machines? Even on the ones where it's working fine?

**Comment by tmylk** [comment]
@AritzBi Could you find anything special about this machine?

**Comment by menshikh-iv** [comment]
Unreproducible
