### ISSUE TITLE
hdp_to_lda should return LdaModel instance

### ISSUE THREAD

**Issue by dsquareindia** [RaRe-Technologies/gensim#901]
I was recently using this feature and found that the documentation doesn't mention anything about what [this](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/hdpmodel.py#L510) function returns. It would also help if a short code snippet can be inserted telling that for using this in an LDA model, `alpha` can be set in the `LdaModel` init and `ldam.expElogbeta[:]` can be set as the `beta` in the new LdaModel.

**Comment by dsquareindia** [comment]
@tmylk I was wondering that wouldn't it be better to return a proper LdaModel instance itself as do in say `malletmodel2ldamodel`?

**Comment by tmylk** [comment]
Agree that returning an actual `LDAModel` is more explicit. That would be a good improvement.

**Comment by dsquareindia** [comment]
Alright! I'll wait for a while for someone to take this up.

**Comment by bhargavvader** [comment]
I don't mind giving this a shot! Though I can try some other issue if this would be a good `beginner` issue for someone else.

**Comment by dsquareindia** [comment]
@bhargavvader are you taking this up? I'll take this up this weekend otherwise :)

**Comment by bhargavvader** [comment]
Yup, on it!

**Comment by bhargavvader** [comment]
Also, @dsquareindia , the reason it returns `alpha` and `beta` and not a model is because in it's inference it uses that method to get the updated `alpha` and `beta` values. You can see line [246](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/hdpmodel.py#L246) for an example of this.

So what I'm going to do is add an extra parameter, which instead returns an `ldamodel` instead of the alpha and beta values, but let the default behaviour be to return these values, and something in the docs about how this needs to be done.

@tmylk is that ok?

**Comment by tmylk** [comment]
A new method would be better.

**Comment by bhargavvader** [comment]
Yeah, #996 implements a new method.

**Comment by bhargavvader** [comment]
@dsquareindia can this be closed? #1055 fixes this.
