### ISSUE TITLE
Create a cumulative-distribution table.

### ISSUE THREAD

**Issue by Ulitochka** [RaRe-Technologies/gensim#991]
Hello!

Could you please give a link to paper, with a description of the method, which you use in make_cum_table() ? Because I dont't understand that is "cumulative" in string: cumulative += self.vocab[self.index2word[word_index]].count**power / train_words_pow. Is this a relative cumulative frequency?

**Comment by gojomo** [comment]
It is mimicking the calculation in the original word2vec.c code (where the exponentiation softens the difference between words of different frequencies):

https://github.com/tmikolov/word2vec/blob/d83ccfba4dd08f113d5e75d67c9f6cd30f6532c4/word2vec.c#L52

But, in gensim it's been optimized to use less memory. It just stores the indexes where a word's 'draws' begin and end. Thus lookup requires a binary-search (in a compact list of transition-indexes) instead of direct-lookup-of-a single-slot (in a giant structure). Other than the two sets of source code, I don't know of other references.

**Comment by Ulitochka** [comment]
Thanks for your answer.
